feat(notice-bar): support direction attr
Tencent/tdesign-miniprogram pull request #1036
Opened 2022-11-16 08:31 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 新特性提交
- [x] 文档改进
- [x] 演示代码改进
- [x] 组件样式/交互改进

### 📝 更新日志

- feat(NoticeBar): 属性 content 新增 Array 类型
- feat(NoticeBar): 属性 suffixIcon 新增 Object 类型透传至图标组件
- feat(NoticeBar): 属性 prefixIcon 新增 Boolean、Object 类型
- feat(NoticeBar): 新增 direction 属性，新支持垂直方向滚动
- feat(NoticeBar): 新增 CSS Variables， 用于调整公告栏文本、背景颜色

2022-11-16 12:53 UTC, LeeJim requested changes

2022-11-16 12:53 UTC, LeeJim commented on src/notice-bar/notice-bar.wxml
> +      <swiper
自行实现上下切换，不要依赖 swiper 更好一些。

2022-11-16 12:53 UTC, LeeJim commented on src/notice-bar/README.md
> +direction | String | horizontal | 滚动方向，可选 horizontal、vertical。可选项：horizontal/vertical | N
可选值不用在描述里写出来

2022-11-16 12:53 UTC, LeeJim commented on src/notice-bar/README.md
> +### 主题定制
后续使用脚本生成

2022-11-18 05:12 UTC, anlyyao commented
@LeeJim  这周我先过“数据展示列”， 下周开始“消息通知”，一起处理～

2022-12-02 01:31 UTC, anlyyao commented on src/notice-bar/README.md
> +### 主题定制
1

2022-12-02 01:31 UTC, anlyyao commented on src/notice-bar/README.md
> +direction | String | horizontal | 滚动方向，可选 horizontal、vertical。可选项：horizontal/vertical | N
1

2022-12-02 06:20 UTC, LeeJim requested changes

2022-12-02 06:20 UTC, LeeJim commented on src/notice-bar/README.en-US.md
> +prefix-icon-props | Object | {} | \- | N
将 prefix-icon 支持 object 就行了，不需要另外新增 property。suffix同理

2022-12-05 11:39 UTC, anlyyao commented on src/notice-bar/README.en-US.md
> +prefix-icon-props | Object | {} | \- | N
1

2022-12-06 13:11 UTC, LeeJim commented
预览

2022-12-08 13:40 UTC, LeeJim approved these changes

2022-12-08 13:41 UTC, merged