feat(Result): support iconProps attr
Tencent/tdesign-miniprogram pull request #1040
Opened 2022-11-16 12:55 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 新特性提交
- [x] 演示代码改进

### 📝 更新日志

- feat(Result): 新增 iconProps 属性
- feat(Result): 新增 CSS Variables， 用于调整标题、描述文本颜色

2022-11-17 02:29 UTC, LeeJim requested changes

2022-11-17 02:29 UTC, LeeJim commented on src/result/result.less
> +@result-icon-default-color: #0052d9;
这里要使用变量，如 @priamry-color

2022-11-17 04:45 UTC, anlyyao commented on src/result/result.less
> +@result-icon-default-color: #0052d9;
1

2022-11-17 04:45 UTC, anlyyao commented on src/result/result.less
>  @result-title-color: rgba(0, 0, 0, 0.9);
1

2022-11-18 01:25 UTC, LeeJim approved these changes

2022-11-18 01:26 UTC, merged