style(CountDown): using css token
Tencent/tdesign-miniprogram pull request #1085
Opened 2022-11-21 10:44 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 组件样式/交互改进
- [x] 代码风格优化

### 📝 更新日志

- feat(CountDown): size 属性默认值变更为 `medium`
- feat(CountDown): 新增 CSS Variables， 用于调整倒计时背景、文本颜色

2022-11-24 02:52 UTC, LeeJim requested changes
CSS需要注意一下，使用 BEM ，尽量避免后代选择器

2022-11-24 02:52 UTC, LeeJim commented on src/count-down/README.md
> +theme | String `v0.5.1` | 'default' | 倒计时风格。可选项：default/round/square/none | N
本身有个主题是 highlight 就不要改成 none 了

2022-11-24 02:52 UTC, LeeJim commented on src/count-down/_example/count-down.wxml
> +<t-demo padding title="01 类型">
组件类型

2022-11-24 02:52 UTC, LeeJim commented on src/count-down/_example/count-down.wxml
> +<t-demo padding title="02 尺寸" desc="倒计时 large/medium/small 尺寸">
组件尺寸

2022-11-24 02:52 UTC, LeeJim commented on src/count-down/_example/sizeCountDown/index.wxss
> +.demo-count-down {
文件名用 size 就 OK了

2022-11-24 02:52 UTC, LeeJim commented on src/count-down/count-down.less
> +@countdown-round-color: var(--td-countdown-round-color, @font-white-1);
backgroundColor 统一使用一个就够了

2022-11-24 02:52 UTC, LeeJim commented on src/count-down/count-down.less
> +  &--none {
全部主题都要加的话，是不是就可以省略了

2022-11-24 12:27 UTC, anlyyao commented on src/count-down/_example/count-down.wxml
> +<t-demo padding title="01 类型">
1

2022-11-24 12:27 UTC, anlyyao commented on src/count-down/_example/count-down.wxml
> +<t-demo padding title="02 尺寸" desc="倒计时 large/medium/small 尺寸">
1

2022-11-24 12:28 UTC, anlyyao commented on src/count-down/_example/sizeCountDown/index.wxss
> +.demo-count-down {
1

2022-11-24 12:28 UTC, anlyyao commented on src/count-down/count-down.less
> +@countdown-round-color: var(--td-countdown-round-color, @font-white-1);
1

2022-11-24 12:29 UTC, anlyyao commented on src/count-down/count-down.less
> +  &--none {
1

2022-11-25 02:12 UTC, anlyyao commented on src/count-down/README.md
> +theme | String `v0.5.1` | 'default' | 倒计时风格。可选项：default/round/square/none | N
1

2022-11-25 13:58 UTC, LeeJim requested changes
highlight 不是 light

2022-11-26 09:38 UTC, LeeJim approved these changes

2022-11-26 09:39 UTC, merged