feat(Textarea): enrich attributes
Tencent/tdesign-miniprogram pull request #1097
Opened 2022-11-22 12:47 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [x] 文档改进
- [x] 演示代码改进
- [x] 组件样式/交互改进

### 📝 更新日志

- fix(Textarea): 更新 maxlength 默认值为 -1。
- feat(Textarea): 新增 placeholderStyle、fixed 、bordered、 indicator 等属性
- feat(Textarea): 新增 CSS Variables， 用于调整文本框背景、输入文本颜色

2022-11-24 06:45 UTC, LeeJim requested changes

2022-11-24 06:45 UTC, LeeJim commented on src/textarea/textarea.wxml
> +      class="{{classPrefix}}__wrapper-textarea {{disabled? classPrefix +  '--disabled' : ''}} {{prefix}}-class-textarea"
这个类名不符合 BEM 规范。
disabled 修饰的是 classPrefix 是不对的，应该`{{classPrefix}}__wrapper-textarea`
另外类名建议修改下，改成 `{{classPrefix}}__host`

2022-11-24 06:45 UTC, LeeJim commented on src/textarea/textarea.less
> +@textarea-placeholder-color: var(--td-textarea-placeholder-color, rgba(0, 0, 0, 0.4));
使用变量

2022-11-24 06:45 UTC, LeeJim commented on src/textarea/textarea.less
> +@textarea-indicator-text-padding-top: var(--td-textarea-indicator-text-padding-top, 8px);
CSS Variables 不用拆这么细

2022-11-24 11:45 UTC, anlyyao commented on src/textarea/textarea.less
> +@textarea-placeholder-color: var(--td-textarea-placeholder-color, rgba(0, 0, 0, 0.4));
1

2022-11-24 11:45 UTC, anlyyao commented on src/textarea/textarea.less
> +@textarea-indicator-text-padding-top: var(--td-textarea-indicator-text-padding-top, 8px);
1

2022-11-24 11:57 UTC, anlyyao commented on src/textarea/textarea.wxml
> +      class="{{classPrefix}}__wrapper-textarea {{disabled? classPrefix +  '--disabled' : ''}} {{prefix}}-class-textarea"
1

2022-11-25 03:40 UTC, LeeJim approved these changes

2022-11-25 03:42 UTC, LeeJim approved these changes

2022-11-25 03:43 UTC, merged