feat(Input): enrich attributes
Tencent/tdesign-miniprogram pull request #1109
Opened 2022-11-24 09:41 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 新特性提交
- [x] 文档改进
- [x] 演示代码改进
- [x] 组件样式/交互改进

### 📝 更新日志

- feat(Input): 完善 status 和 tips 属性
- feat(Input): 新增 layout 属性
- feat(Input): 外部样式新增 t-class-tips， t-class-icon 变更为 t-class-prefix-icon
- feat(Input): 新增 CSS Variables
- feat(Input): borderless 属性更名为 bordered
- feat(Input): size 属性默认值变更为 medium
- chore(Input): 移除 errorMessage 属性相关代码

2022-11-25 13:58 UTC, LeeJim requested changes

2022-11-25 14:41 UTC, anlyyao commented on src/input/input.less
> +  box-shadow: 0 1px 10px 0 rgba(0, 0, 0, 0.05), 0 4px 5px 0 rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.12);
1

2022-11-25 15:04 UTC, anlyyao commented on src/input/input.less
> +.@{prefix}-is-border {
1

2022-11-25 15:04 UTC, anlyyao commented on src/input/README.md
> +bordered | Boolean | false | 是否显示外边框 | N
1

2022-11-28 02:00 UTC, LeeJim commented
冲突了

2022-11-28 14:39 UTC, merged