style(BackTop): using css token
Tencent/tdesign-miniprogram pull request #1151
Opened 2022-12-01 04:40 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x ] 演示代码改进
- [x] 组件样式/交互改进

### 📝 更新日志

- feat(BackTop): 新增 CSS Variables

2022-12-02 06:03 UTC, LeeJim requested changes

2022-12-02 06:03 UTC, LeeJim commented on src/back-top/back-top.less
>    &.@{prefix}-is-round,
可以重构下类名，使用 `--fixed` 这样的修饰符

2022-12-02 06:03 UTC, LeeJim commented on src/back-top/back-top.wxml
> +  <t-icon
可以参考下 common/template 写成模板 方便其他组件要透传 iconProps 时使用

2022-12-05 08:17 UTC, anlyyao commented on src/back-top/back-top.less
>    &.@{prefix}-is-round,
1

2022-12-05 08:17 UTC, anlyyao commented on src/back-top/back-top.wxml
> +  <t-icon
1

2022-12-05 08:49 UTC, LeeJim requested changes

2022-12-05 08:49 UTC, LeeJim commented on src/back-top/back-top.less
> +  &.@{backtop}--fixed {
这样的构建出来的结果是：`.t-back-top.t-back-top--fixed` 这样就使用了两个 class 了。
建议使用：`&--fixed`。
下面同理

2022-12-05 08:49 UTC, LeeJim commented on src/back-top/back-top.ts
> +        icon,
不要使用同一个变量，另外需要监听 icon 变化

2022-12-05 09:31 UTC, anlyyao commented on src/back-top/back-top.less
> +  &.@{backtop}--fixed {
1

2022-12-08 03:23 UTC, LeeJim requested changes

2022-12-08 03:23 UTC, LeeJim commented on src/back-top/back-top.less
> +    > .@{backtop}__text {
不要用这个子选择器，给 text 加上 --half-round 这些修饰符就好了

2022-12-08 03:23 UTC, LeeJim commented on src/back-top/back-top.less
> +    > .@{backtop}__icon:not(:empty) + .@{backtop}__text {
同理

2022-12-08 05:49 UTC, anlyyao commented on src/back-top/back-top.less
> +    > .@{backtop}__text {
1

2022-12-08 05:49 UTC, anlyyao commented on src/back-top/back-top.less
> +    > .@{backtop}__icon:not(:empty) + .@{backtop}__text {
1

2022-12-08 13:28 UTC, LeeJim approved these changes

2022-12-08 13:28 UTC, merged