feat(Progress): new component
Tencent/tdesign-miniprogram pull request #1178
Opened 2022-12-07 08:06 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 重构

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- feat(Progress): 新增 CSS Variables， 用于调整进度条背景颜色
- feat(Progress): 完善 theme 属性，支持 'plump'  和 'circle' 类型

2022-12-08 14:18 UTC, LeeJim requested changes
demo背景色不对

2022-12-08 14:18 UTC, LeeJim commented on src/common/utils.ts
> +export const changeUnitToPx = function (e: number | string) {
rebase develop 会有个新的方法：unitConvert 可以直接用

2022-12-09 01:55 UTC, anlyyao commented on src/common/utils.ts
> +export const changeUnitToPx = function (e: number | string) {
1 已更新，demo背景色已对齐视觉

2022-12-09 03:30 UTC, LeeJim approved these changes
LGTM

2022-12-09 03:30 UTC, merged