fix(toast): hide noactive-content, screen-reader can be to read the message
Tencent/tdesign-miniprogram pull request #1210
Opened 2022-12-11 09:24 UTC by huaiyinfeilong

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

#1029 

### 💡 需求背景和解决方案

* 屏蔽装饰性元素读屏聚焦
* toast文本内容弹出后，读屏自动播报

Android录屏：
https://share.weiyun.com/dflI08ih

iOS录屏：
https://share.weiyun.com/7N47AvzI

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-12-11 10:15 UTC, syxysszyw commented
预览

2022-12-12 06:20 UTC, syxysszyw commented
预览

2022-12-12 06:25 UTC, syxysszyw approved these changes
LGTM

2022-12-12 06:43 UTC, LeeJim requested changes

2022-12-12 06:43 UTC, LeeJim commented on src/toast/toast.wxml
> +      aria-hidden="true"
hidden 是 boolean 类型，这样结果符合预期是因为 `Boolean('true') === true`。
建议直接使用 `aira-hidden` 即可，或者 `aira-hidden="{{true}}"`

2022-12-12 06:43 UTC, LeeJim commented on src/toast/toast.wxml
> +      aria-atomic="true"
这个和上面是一样的问题

2022-12-12 08:26 UTC, huaiyinfeilong commented on src/toast/toast.wxml
> +      aria-atomic="true"
上述问题已修复 
#1210

2022-12-14 07:04 UTC, LeeJim approved these changes

2022-12-14 07:05 UTC, merged