feat(Link): new component
Tencent/tdesign-miniprogram pull request #1236
Opened 2022-12-16 10:20 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 新特性提交

### 📝 更新日志

- feat(Link): 新增 Link 组件

2022-12-18 15:20 UTC, LeeJim requested changes

2022-12-18 15:20 UTC, LeeJim commented on src/input/input.less
> +.test {
? 测试代码

2022-12-18 15:20 UTC, LeeJim commented on src/link/link.less
> +@link-color-default-normal: var(--td-link-color-default-normal, @font-gray-1); // default 主题默认态颜色
命名统一下，类似这样：`@link-normal-default-color`

2022-12-19 03:41 UTC, anlyyao commented on src/input/input.less
> +.test {
已移除。

2022-12-19 03:41 UTC, anlyyao commented on src/link/link.less
> +@link-color-default-normal: var(--td-link-color-default-normal, @font-gray-1); // default 主题默认态颜色
1

2022-12-20 07:05 UTC, LeeJim approved these changes

2022-12-20 07:14 UTC, merged