feat(upload): support aria
Tencent/tdesign-miniprogram pull request #1238
Opened 2022-12-17 04:47 UTC by zhangpaopao0609

### 🤔 这个 PR 的性质是？

- [x] 新特性提交

### 🔗 相关 Issue

fix #1063 

### 💡 需求背景和解决方案

ios 录屏

### 📝 更新日志

- feat(Upload): 支持无障碍访问

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-12-17 05:18 UTC, zhangpaopao0609 commented
还是存在问题的
1. 点击图片时的播报，预期播报：`图像，按钮`，但因为 内部使用 `grid` 实现，如果图片为 按钮，那么这之上的所有都无法聚焦了，包括： `x`, `上传状态`

2022-12-17 06:03 UTC, zhangpaopao0609 commented
> 还是存在问题的
> 
> 1. 因为内部使用 `grid` 实现，所有的元素都包裹在 grid-item 之下（grid-item 默认 role 为 button），如果外层 grid-item 为 button ，那么 grid-item 中所有的元素都将无法聚焦，包括： `x`，上传状态说明
> 
> * 其中的上传状态可以直接在 grid-item 中传 label 来实现，但 `x` 按钮始终是个问题
> 
> 想到的改动较少的办法是 第一步： hack grid-item 的 role，例如指定为 `presentation` 第二步：将 “图片结构” 和 “删除按钮结构” 修改为兄弟结构而不是父子 第三步：“图片结构” role 为 button，label 根据文件类型和状态类动态设置；“删除按钮结构” role 为 button，label 为删除

已按照次思路实现初步，不过代码还有很大问题

2022-12-17 08:34 UTC, syxysszyw commented
<img width="393" alt="image" src="https://user-images.githubusercontent.com/4988284/208233416-3f1fe883-a315-41ff-be4c-9bbc67b14e09.png">

2022-12-18 02:46 UTC, zhangpaopao0609 commented
> <img alt="image" width="393" src="https://user-images.githubusercontent.com/4988284/208233416-3f1fe883-a315-41ff-be4c-9bbc67b14e09.png">

这个从代码层面看是支持点击的，只是点击后 ui 上没有效果，这个是否要设置为 button 可以考虑

2023-02-06 03:35 UTC, syxysszyw commented
预览3

2023-02-06 03:56 UTC, syxysszyw commented
1. “上传图片”示例的图标按钮在安卓机下不读

https://user-images.githubusercontent.com/4988284/216880472-c3948ecd-24a3-4a34-bd50-a1244b63646a.mp4

2023-02-06 03:59 UTC, syxysszyw commented on src/upload/upload.wxml
> +          aria-label="{{file.status && file.status != 'done' ? file.status == 'loading' ? file.percent ? '上传中' + file.percent + '%' : '上传中' : file.status == 'reload' ? '重新上传' : '上传失败' : file.type ===
这里的判断有些复杂，有没有可能简化一下？或者适当添加`()`？

2023-02-07 06:51 UTC, zhangpaopao0609 commented on src/upload/upload.wxml
>      >
1

2023-02-07 06:51 UTC, zhangpaopao0609 commented on src/upload/upload.wxml
> +      aria-label="上传文件"
1

2023-02-07 07:05 UTC, zhangpaopao0609 commented on src/upload/upload.wxml
> +          aria-label="{{file.status && file.status != 'done' ? file.status == 'loading' ? file.percent ? '上传中' + file.percent + '%' : '上传中' : file.status == 'reload' ? '重新上传' : '上传失败' : file.type ===
这里的可读性确实有点差，我想换行会报错，相较合适的方法应该是将这个逻辑放到函数中处理。

我这里先加上括号吧，然后辛苦 @LeeJim 帮忙看看转移到 ts 中

2023-02-13 02:23 UTC, LeeJim commented on src/upload/upload.wxml
> +          aria-label="{{file.status && file.status != 'done' ? file.status == 'loading' ? file.percent ? '上传中' + file.percent + '%' : '上传中' : file.status == 'reload' ? '重新上传' : '上传失败' : file.type ===
这里改成使用 wxs ，可读性会好一些

2023-02-14 08:59 UTC, LeeJim requested changes

2023-02-14 08:59 UTC, LeeJim commented on src/upload/upload.wxml
> +          class="{{classPrefix}}__wrapper"
这个wrapper和外面的重复了，看下能否合并

2023-02-14 08:59 UTC, LeeJim commented on src/upload/upload.wxml
> +          aria-label="{{(file.status && file.status != 'done') ? (file.status == 'loading' ? (file.percent ? '上传中' + file.percent + '%' : '上传中') : (file.status == 'reload' ? '重新上传' : '上传失败')) : (file
这部分最好使用 wxs 写，这样可读性比较差

2023-02-14 10:12 UTC, zhangpaopao0609 commented on src/upload/upload.wxml
> +          aria-label="{{(file.status && file.status != 'done') ? (file.status == 'loading' ? (file.percent ? '上传中' + file.percent + '%' : '上传中') : (file.status == 'reload' ? '重新上传' : '上传失败')) : (file
1

2023-02-14 10:12 UTC, zhangpaopao0609 commented on src/upload/upload.wxml
> +          class="{{classPrefix}}__wrapper"
1

2023-02-14 10:12 UTC, zhangpaopao0609 commented on src/upload/upload.wxml
> +          aria-label="{{file.status && file.status != 'done' ? file.status == 'loading' ? file.percent ? '上传中' + file.percent + '%' : '上传中' : file.status == 'reload' ? '重新上传' : '上传失败' : file.type ===
1

2023-02-16 07:13 UTC, LeeJim approved these changes

2023-02-16 07:13 UTC, LeeJim commented on src/upload/upload.wxs
> +    if (file.type === 'video') {
可以简化一下 `return file.type === 'video' ? '视频' : '图像'`。
上面两个同理

2023-02-16 07:23 UTC, syxysszyw commented
预览1

2023-02-16 07:32 UTC, LeeJim approved these changes

2023-02-16 07:37 UTC, syxysszyw commented
发现一个兼容性问题，安卓下“上传、按钮”这个图标都不读（2台安卓手机、不同版本的读屏软件都试过）

https://user-images.githubusercontent.com/4988284/219298579-0d0f5757-374f-4bca-95a1-d63a0a9b6eb3.mp4

2023-02-16 07:42 UTC, syxysszyw commented on src/upload/upload.wxml
> +      aria-label="上传"
这里需要补充一下 `aria-role=button`？

2023-02-16 07:51 UTC, syxysszyw commented
预览2

2023-02-16 08:05 UTC, syxysszyw commented on src/upload/upload.wxml
> +      aria-label="上传"
搞错了😂 ，不是aria-role=button的问题，本身录屏是能读出“按钮”的

是声明了aria-label传不进grid-item里面

2023-02-16 08:17 UTC, syxysszyw commented
预览3

2023-03-01 03:09 UTC, syxysszyw commented
预览1

2023-03-01 03:27 UTC, syxysszyw commented on src/grid-item/grid-item.ts
> +    describeID: '',
descriptionID  或 describedbyID ?

2023-03-01 03:27 UTC, syxysszyw commented on src/upload/upload.wxml
> +        aria-label="{{this.getWrapperAriaLabel(file)}}"
aria-role 和 aria-label 都支持一下自定义

2023-03-01 03:27 UTC, syxysszyw commented on src/upload/upload.wxml
> +      <view
“删除”的结构有些调整， @LeeJim 帮忙也确认下

2023-03-01 03:56 UTC, zhangpaopao0609 commented on src/upload/upload.wxml
> +        aria-label="{{this.getWrapperAriaLabel(file)}}"
1

2023-03-01 03:56 UTC, zhangpaopao0609 commented on src/grid-item/grid-item.ts
> +    describeID: '',
1

2023-03-01 07:13 UTC, LeeJim approved these changes

2023-03-01 07:13 UTC, LeeJim commented on src/upload/upload.wxml
> +      <view
OK的，没什么问题

2023-03-01 07:23 UTC, merged