feat(Input): support click event
Tencent/tdesign-miniprogram pull request #1247
Opened 2022-12-19 09:16 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [x] 新特性提交

### 🔗 相关 Issue
#1202 
#1230 
#1209 

### 💡 需求背景和解决方案
input聚焦样式问题： 原生 input 组件 focus 事件存在延迟，聚焦样式体验较差，故移除聚焦相关样式。
后缀内容增加点击事件：已新增 click 事件，并补齐使用示例。

### 📝 更新日志

- style(Input): 移除聚焦相关样式
- feat(Input): 新增 click 事件

2022-12-20 02:54 UTC, LeeJim commented
预览

2022-12-20 06:35 UTC, LeeJim requested changes

2022-12-20 06:35 UTC, LeeJim commented on src/input/README.md
> +click | `(trigger: InputTrigger)` | 点击事件。[详细类型定义](https://github.com/Tencent/tdesign-miniprogram/tree/develop/src/input/type.ts)。<br/>`type InputTrigger = 'suffix' \| 'suffix-icon';`<br/>
增加下支持版本，0.32.0

2022-12-20 07:30 UTC, anlyyao commented on src/input/README.md
> +click | `(trigger: InputTrigger)` | 点击事件。[详细类型定义](https://github.com/Tencent/tdesign-miniprogram/tree/develop/src/input/type.ts)。<br/>`type InputTrigger = 'suffix' \| 'suffix-icon';`<br/>
1 已补充

2022-12-27 02:02 UTC, LeeJim commented
> <img alt="image" width="1081" src="https://user-images.githubusercontent.com/7017290/209599379-82267751-f88a-4edd-bf70-09ed395fbba7.png">

不要用 @font-size 去乘，直接给个具体数值即可。

2022-12-27 03:56 UTC, LeeJim approved these changes

2022-12-27 03:56 UTC, merged