feat(steps):无障碍支持
Tencent/tdesign-miniprogram pull request #1253
Opened 2022-12-20 08:59 UTC by shinyina

feat #1059

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

feat #1059 

### 💡 需求背景和解决方案

aria合并焦点，根据readonly判断是否是按钮

### 📝 更新日志

- feat(steps):无障碍支持

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供
### 录屏
IOS:

https://user-images.githubusercontent.com/92632534/208623507-98c93fd9-775a-4605-a1e4-cb7ec2c8c5af.mp4

Android:

https://user-images.githubusercontent.com/92632534/208625901-588538e4-a1b8-4528-9014-79293c3ac64a.mp4

2022-12-28 11:28 UTC, syxysszyw commented on src/steps/step-item.wxml
> +  aria-role="{{ariaReadonly}}"
这里建议支持用户传入自定义的 `aria-role` 覆盖组件默认的设置，如：
`aria-role="{{ariaRole || ariaReadonly}}"`

另一个是 `ariaReadonly` 是不是可以优化一下命名呀，例如改成 `ariaRoleName`或其他 ？

2023-01-03 12:00 UTC, shinyina commented on src/steps/step-item.wxml
> +  aria-role="{{ariaReadonly}}"
已修改

2023-01-04 09:00 UTC, syxysszyw commented
预览4

2023-01-04 09:09 UTC, syxysszyw commented on src/steps/step-item.ts
> +        this.parent = parent;
这一行代码是期望达成什么效果呀？是有必要的吗？

2023-01-04 09:11 UTC, shinyina commented on src/steps/step-item.ts
> +        this.parent = parent;
这个是原本就有的，我昨天修改后不知道为什么算我的changes了

2023-01-04 09:29 UTC, syxysszyw commented
切换步骤后，步骤条不同位置读屏播报的文案与实际文案对不上
https://user-images.githubusercontent.com/4988284/210524401-ba2e481e-6611-4477-92fc-7227c1daaf34.mp4

2023-01-06 10:02 UTC, shinyina commented
我这边的话没有这个问题

https://user-images.githubusercontent.com/92632534/210977939-da008810-1cf5-4b3a-9249-68f138be6f22.mp4

2023-01-30 07:07 UTC, syxysszyw commented
方便提供一下手机机型、系统版本、录屏使用的读屏软件版本吗？

2023-01-30 08:27 UTC, shinyina commented
Mi 10
Android12 MIUI13.0.6稳定版
talkback版本 13.1

2023-01-30 08:27 UTC, shinyina commented
Mi 10
Android12 MIUI13.0.6稳定版
talkback版本 13.1

2023-01-30 08:51 UTC, syxysszyw commented
预览9

2023-01-30 09:21 UTC, syxysszyw commented
预览9

2023-01-30 09:33 UTC, LeeJim requested changes

2023-01-30 11:16 UTC, syxysszyw commented
预览9

2023-01-30 11:20 UTC, syxysszyw commented
之前录屏是用 TalkBack 8 体验的，升级到 13 之后就不会有问题了

2023-02-02 07:21 UTC, syxysszyw commented
这里需要解决下冲突哦

2023-02-23 06:47 UTC, syxysszyw commented
hello， @shinyina 好，辛苦抽空帮忙处理下冲突再重新提交一下 ：）

2023-03-09 07:12 UTC, LeeJim commented
@shinyina 还有时间跟进处理下吗

2023-03-16 03:02 UTC, LeeJim commented
#1783，#1722 已完成该 PR 对应的 issue

2023-03-16 03:02 UTC, closed without merging