feat(sidebar): 无障碍支持
Tencent/tdesign-miniprogram pull request #1260
Opened 2022-12-21 08:55 UTC by shinyina

feat #1255

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

feat #1255

### 💡 需求背景和解决方案

*  “选项”和“标题”在实际中应该会是具体文本所以未做修改
*  第三点和第四点应该是t-cell的问题

### 📝 更新日志

-feat(sidebar): 无障碍支持

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供
录屏:
Androd:

https://user-images.githubusercontent.com/92632534/208862008-fbdd98cc-a407-4108-8bbb-62aa9a26cc2a.mp4

2022-12-28 11:43 UTC, syxysszyw commented on src/side-bar-item/side-bar-item.ts
> +      ariaActive = '已禁用';
按钮的“已禁用”状态可以用 `aria-disabled` 来声明（不过目前小程序下支持度还有一些问题，已经反馈给微信官方了）

2022-12-28 11:43 UTC, syxysszyw commented on src/side-bar-item/side-bar-item.wxml
> +  class="{{_.cls(classPrefix, [['active', active], ['disabled', disabled]])}}"
这一行是不是漏掉了 ` {{prefix}}-class` 呀？

2023-01-03 11:46 UTC, shinyina commented on src/side-bar-item/side-bar-item.ts
> +      ariaActive = '已禁用';
已修改

2023-01-03 11:46 UTC, shinyina commented on src/side-bar-item/side-bar-item.wxml
> +  class="{{_.cls(classPrefix, [['active', active], ['disabled', disabled]])}}"
已修改

2023-01-04 09:00 UTC, syxysszyw commented
预览3

2023-01-04 09:27 UTC, syxysszyw commented
1. 请同步最新的develop分支
2. 切换左侧导航，选中态变化了，但“已选中”文案并没有跟着最新的状态变化，导致选中后的选项未能读出“已选中”状态（视频定位00：11），而非选中态的导航依旧保持了“已选中”状态

https://user-images.githubusercontent.com/4988284/210524167-5d8deed0-ac02-4e76-9cb7-8c3afa589f0a.mov

2023-01-06 09:42 UTC, shinyina commented
已修改

2023-01-30 06:58 UTC, syxysszyw commented
hi， @shinyina 辛苦同步一下最新 develop 分支

2023-01-30 08:23 UTC, shinyina commented
已同步

2023-01-30 08:47 UTC, syxysszyw commented
预览1

2023-01-30 09:28 UTC, syxysszyw commented
预览1

2023-01-30 11:41 UTC, syxysszyw commented
预览7

2023-01-30 12:16 UTC, syxysszyw commented
预览7

2023-01-30 12:22 UTC, syxysszyw approved these changes
LGTM

2023-02-01 02:56 UTC, LeeJim requested changes

2023-02-01 02:56 UTC, LeeJim commented on src/side-bar-item/side-bar-item.ts
> +    active() {
这个是不是可以直接写到 wxml 里

2023-02-03 02:05 UTC, LeeJim commented
#1355 已实现

2023-02-03 02:05 UTC, closed without merging