fix(Input): update style
Tencent/tdesign-miniprogram pull request #1381
Opened 2023-01-03 07:28 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
fix #1329 

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(Input): 移除 size 属性
- fix(Input): borderless 属性更名为 bordered 

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-01-03 14:51 UTC, LeeJim requested changes

2023-01-03 14:51 UTC, LeeJim commented on src/input/README.md
> +bordered | Boolean | true | 是否显示外边框 | N
这个变更的目的是什么？

2023-01-03 14:51 UTC, LeeJim commented on src/input/README.md
> +size | String | medium | 【开废弃】输入框尺寸。可选项：small/medium。TS 类型：`'medium' \| 'small'` | N
为什么移除？另外，有错别字

2023-01-04 03:11 UTC, anlyyao commented on src/input/README.md
> +size | String | medium | 【开废弃】输入框尺寸。可选项：small/medium。TS 类型：`'medium' \| 'small'` | N
size 移除 已和设计确认。 错别字已更正 ～

2023-01-04 03:11 UTC, anlyyao commented on src/input/README.md
> +bordered | Boolean | true | 是否显示外边框 | N
最后结论是： 统一使用 borderless，这里将默认值更为 false

2023-01-04 09:27 UTC, LeeJim approved these changes

2023-01-04 09:27 UTC, merged