fix(grid | cell | tabs | tabbar | sliderBar):  badge 动态朗读异常
Tencent/tdesign-miniprogram pull request #1428
Opened 2023-01-06 08:17 UTC by yaogengzhu

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
fix: #1405 

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-01-06 08:32 UTC, syxysszyw commented on src/grid/grid-item.wxml
> +        aria-label="{{ badgeProps.dot || badgeProps.count ? text + ',' +  description + ',' + _.getBadgeAriaLabel({ ...badgeProps }) : ariaLabel }}"
用户自定义的 `ariaLabel` 是不是应该优先级更高？

2023-01-06 08:32 UTC, syxysszyw commented on src/tab-bar/tab-bar-item.wxml
> +      <t-icon wx:else name="{{icon}}" size="{{iconOnly ? 24 : 20}}" aria-hidden="{{iconOnly ? false : true}}" />
这里为什么把 `aria-label` 去掉啦？

2023-01-06 08:33 UTC, yaogengzhu commented on src/tab-bar/tab-bar-item.wxml
> +      <t-icon wx:else name="{{icon}}" size="{{iconOnly ? 24 : 20}}" aria-hidden="{{iconOnly ? false : true}}" />
这看起来不能用这个 aria-label ，套用起来没用了

2023-01-06 08:34 UTC, syxysszyw commented
预览2

2023-01-06 08:35 UTC, yaogengzhu commented on src/grid/grid-item.wxml
> +        aria-label="{{ badgeProps.dot || badgeProps.count ? text + ',' +  description + ',' + _.getBadgeAriaLabel({ ...badgeProps }) : ariaLabel }}"
嗯 我弄反了，😂

2023-01-06 08:51 UTC, syxysszyw commented
安卓手机下，Tabbar、Tabs带Badge的场景会播报2次内容

https://user-images.githubusercontent.com/4988284/210965927-34817175-85cc-456d-a294-64f4f313c43b.mp4

https://user-images.githubusercontent.com/4988284/210965947-dfabf052-963b-4753-8369-38117ee87324.mp4

2023-01-06 09:25 UTC, yaogengzhu commented
> 安卓手机下，Tabbar、Tabs带Badge的场景会播报2次内容
好的。我处理下

2023-01-10 06:55 UTC, syxysszyw commented
预览2

2023-01-10 08:31 UTC, syxysszyw commented
Tabbar 标签文案读不出来 

https://user-images.githubusercontent.com/4988284/211500356-cf73b400-025e-4322-bd81-b40fb7befb95.mp4

2023-01-10 08:38 UTC, yaogengzhu commented
> Tabbar 标签文案读不出来
> 
>  69_1673334975.mp4

这个组件好像每个提供这个可读的文本，需要手动拼接这个文本。看组件是不是可以优化下

2023-01-10 08:42 UTC, syxysszyw commented
>> Tabbar 标签文案读不出来
>> 
>>  69_1673334975.mp4
>
>这个组件好像每个提供这个可读的文本，需要手动拼接这个文本。看组件是不是可以优化下

"每个提供这个可读的文本"怎么理解呀？需要Tabbar支持什么？

2023-01-11 08:52 UTC, syxysszyw commented on src/side-bar-item/side-bar-item.wxml
> +  aria-label="{{ badgeProps.dot || badgeProps.count ? active ? '已选中' + label + _.getBadgeAriaLabel({ ...badgeProps }) : label + _.getBadgeAriaLabel({ ...badgeProps }) : ariaLabel }}"
这里 ariaLabel 的优先级为什么比 badge 的低呀？

2023-01-11 09:06 UTC, syxysszyw commented
预览2

2023-01-12 02:52 UTC, syxysszyw commented
预览2

2023-01-12 06:18 UTC, syxysszyw commented
预览2

2023-01-30 02:57 UTC, syxysszyw commented
预览1

2023-01-30 03:10 UTC, LeeJim commented
预览4

2023-01-30 06:18 UTC, yaogengzhu commented
预览5

2023-01-31 10:33 UTC, syxysszyw commented
预览5

2023-01-31 11:01 UTC, syxysszyw commented
预览5

2023-01-31 12:32 UTC, syxysszyw commented
预览6

2023-02-08 08:36 UTC, syxysszyw commented
预览3

2023-02-08 09:40 UTC, syxysszyw commented
预览3

2023-02-23 06:52 UTC, yaogengzhu commented
预览2

2023-03-01 04:53 UTC, yaogengzhu commented
预览

2023-03-01 04:53 UTC, yaogengzhu commented
预览1

2023-03-01 06:11 UTC, yaogengzhu commented
预览3

2023-03-01 06:38 UTC, syxysszyw commented
预览1

2023-03-01 07:20 UTC, syxysszyw commented
1. 视频定位00：02，图标未定义label？目前无法确定纯图标Badge是否能读出图标的label，建议给图标加上 `ariaLabel="通知"`试试

https://user-images.githubusercontent.com/4988284/222068923-d1ef78e0-149b-4638-bb59-0d04bed224ee.MP4

2. 上述视频定位00：18，读的是“有新的消息”；期望是读出“领积分”

3. Tabbar 带了 Badge 的示例，无法读出 label（“首页”、“软件”、“聊天”、“我的”）内容，安卓和苹果手机都不读

https://user-images.githubusercontent.com/4988284/222069188-beedcb87-fe69-4764-bad9-69707faef263.MP4

其中，Tabbar读出label的效果如视频所示（预期效果是在现有朗读效果的基础上，可以正确读出Badge的附加信息）：

https://user-images.githubusercontent.com/4988284/222070416-c28c183c-b483-490e-9d15-6d952594c199.MP4

2023-03-01 10:51 UTC, yaogengzhu commented
回复1 ： 这种应该不能交由组件来定义了，icon类型太多了，用户自定义比较好。
回复2： 期望是读出“领积分” ，这个之前是这么做的，但是发现组件存在红点 以及 ... （new）等一些特殊的符号，就没法详细的区分了，因此统一了概念 （有新的消息和 几条消息）

2023-03-01 11:15 UTC, yaogengzhu commented
https://user-images.githubusercontent.com/42566669/222123979-640f8060-9851-4953-ac71-f1e9ec189cdb.mp4

2023-03-01 11:36 UTC, syxysszyw commented
> 回复1 ： 这种应该不能交由组件来定义了，icon类型太多了，用户自定义比较好。
> 回复2： 期望是读出“领积分” ，这个之前是这么做的，但是发现组件存在红点 以及 ... （new）等一些特殊的符号，就没法详细的区分了，因此统一了概念 （有新的消息和 几条消息）

1. 确实不应该由组件来定义，我的意思是example需要完善一下
2. 不太符合预期，纯红点和数字分别读成“有新的消息”和“几条消息”，用户自定义文本期望读出自定义内容

2023-03-02 02:36 UTC, yaogengzhu commented
https://user-images.githubusercontent.com/42566669/222316532-2633dbfa-532e-474e-9171-9024a25ce0fc.mp4

2023-03-02 03:17 UTC, syxysszyw commented
预览1

2023-03-02 03:32 UTC, syxysszyw commented on src/badge/_example/base/index.wxml
> +    <t-button icon="notification" ariaLabel="按钮" shape="square" size="large" />
ariaLabel 为什么会是“按钮”呀？

2023-03-02 03:32 UTC, syxysszyw commented on src/tab-bar/_example/badge/index.wxml
> +  <t-tab-bar-item badge-props="{{ {count: 'New'} }}" ariaLabel="聊天，有New通知" value="label3" icon="chat"
这里是不是直接用 “New” 就好了？

2023-03-02 03:34 UTC, syxysszyw commented
“有领积分通知” 是不是可以读成“领积分”就好？

2023-03-02 07:31 UTC, syxysszyw commented on src/badge/_example/base/index.wxml
> +    <t-button icon="notification" ariaLabel="按钮" shape="square" size="large" />
这里试试在 t-badge 那里声明 `aria-role="button"`，t-button 声明 `aria-label="通知"`

2023-03-02 09:18 UTC, anlyyao commented
@yaogengzhu 辛苦rebase一下dev分支，然后执行 npm run test:snap-update，处理一下测试快照问题～

2023-03-02 09:39 UTC, syxysszyw commented
预览1

2023-03-02 10:31 UTC, syxysszyw commented
预览1

2023-03-02 11:29 UTC, syxysszyw commented
预览2

2023-03-03 07:31 UTC, syxysszyw commented
预览2

2023-03-07 14:36 UTC, syxysszyw commented
预览1

2023-03-07 15:51 UTC, syxysszyw commented on src/side-bar-item/side-bar-item.wxml
> +  aria-label="{{ ariaLabel || (badgeProps.dot || badgeProps.count ? (active ? '已选中' + label + _.getBadgeAriaLabel({ ...badgeProps }) : label + _.getBadgeAriaLabel({ ...badgeProps })) : '') }}"
'已选中' 后面增加一个逗号吧，'已选中，'

2023-03-07 15:51 UTC, syxysszyw commented on src/badge/_example/theme/index.wxml
> +  <t-badge count="领积分" shape="bubble" ariaRole="button">
这里帮忙补充一下注释——为什么在t-badge声明ariarole为button，便于后续理解

2023-03-07 15:51 UTC, syxysszyw commented on src/grid-item/grid-item.wxml
> +        aria-label="{{ ariaLabel || (badgeProps.dot || badgeProps.count ? text + ',' +  description + ',' + _.getBadgeAriaLabel({ ...badgeProps }) : '') }}"
PR中关于 aria-label 的写法， @LeeJim 帮看看有没有更好的方式

2023-03-11 02:37 UTC, LeeJim requested changes

2023-03-11 02:37 UTC, LeeJim commented on src/badge/_example/base/index.wxml
> +<view class="demo-desc">数字徽标-</view>
`-` 是预期的吗？应该是要移除的

2023-03-11 02:37 UTC, LeeJim commented on src/grid-item/grid-item.wxml
> +        aria-label="{{ ariaLabel || (badgeProps.dot || badgeProps.count ? text + ',' +  description + ',' + _.getBadgeAriaLabel({ ...badgeProps }) : '') }}"
这里确实没有更好的方式了

2023-03-11 02:37 UTC, LeeJim commented on src/badge/_example/base/index.wxml
> +<view class="demo-desc">数字徽标二</view>
这部分示例还是不要加了，我们的 demo 展示也要按照设计稿来

2023-03-11 06:44 UTC, yaogengzhu commented on src/badge/_example/base/index.wxml
> +<view class="demo-desc">数字徽标二</view>
👌

2023-03-11 06:45 UTC, yaogengzhu commented on src/badge/_example/base/index.wxml
> +<view class="demo-desc">数字徽标-</view>
remove

2023-03-13 03:04 UTC, LeeJim approved these changes

2023-03-13 07:43 UTC, merged