fix(Swiper): only when the user touches the current is updated by set…
Tencent/tdesign-miniprogram pull request #1494
Opened 2023-01-12 08:58 UTC by anlyyao

…Data

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
fix #1391 

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(Swiper): 修复 `autoplay` 状态下，`swiper` 偶现左右抖动问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-01-12 14:32 UTC, LeeJim requested changes
current不是响应式的了

2023-01-13 08:02 UTC, anlyyao commented
> current不是响应式的了

我只能想到两种场景，
1. touch 和 autoplay，这两种都会触发change，并更新current。
2. 外部修改current，也是setData，这样也是会更新到视图，并且会触发change。

所以我在change下同步更新_current，可以达到current和_current值始终一致～

2023-01-17 02:47 UTC, anlyyao commented
> 我的意思是，如果在 ready 之后在外部修改了 current，就没任何反应了

https://user-images.githubusercontent.com/51158141/212798588-3a7bae77-4170-46a6-b092-eac09268a750.mov


我理解是 只要是通过setData修改的 就会符合第二种场景 仍然会触发change、

2023-01-17 07:37 UTC, anlyyao commented
已修改变量为 navCurrent~

2023-01-17 08:44 UTC, LeeJim approved these changes

2023-01-17 08:44 UTC, merged