feat(Cell): enrich CSS Variables
Tencent/tdesign-miniprogram pull request #1515
Opened 2023-01-16 13:07 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
fix #1502 

### 💡 需求背景和解决方案
背景：需要自定义 border 左右边距
方案：补充CSS Variable， 通过  `--td-border-left-space` 和 `--td-border-right-space` 控制底边框左右边距。

### 📝 更新日志

- feat(Cell): 新增底边框左右边距CSS Variables

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-01-16 13:27 UTC, LeeJim requested changes

2023-01-16 13:27 UTC, LeeJim commented on src/cell/_example/cell.less
> +// .demo-section__wrapper {
可以都移除了

2023-01-16 14:20 UTC, anlyyao commented on src/cell/_example/cell.less
> +// .demo-section__wrapper {
1

2023-01-17 02:01 UTC, LeeJim approved these changes

2023-01-17 02:01 UTC, merged