fix(rate): 评分组件支持无障碍滑动
Tencent/tdesign-miniprogram pull request #1574
Opened 2023-02-10 06:34 UTC by byq1213

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

#1050 
### 💡 需求背景和解决方案

### 📝 更新日志

- fix(rate): 评分组件支持无障碍滑动

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-02-10 07:49 UTC, syxysszyw commented
预览2

2023-02-10 11:24 UTC, syxysszyw commented on src/rate/rate.less
> +    &--sr-only {
这种工具类是否可以放在 src/common/style/utilities/_index.less 里？

@LeeJim

2023-02-10 11:24 UTC, syxysszyw commented on src/rate/rate.wxml
> +      aria-role="radio"
这里为什么还要定义`aria-role="radio"` ？

2023-02-10 11:24 UTC, syxysszyw commented on src/rate/rate.wxml
> +    aria-valuemin="{{0}}"
`aria-valuemin` 应该是 1 ？

2023-02-10 11:24 UTC, syxysszyw commented on src/rate/rate.wxml
> +      <t-icon
这里的变更是符合预期的吗？

2023-02-15 08:46 UTC, LeeJim commented on src/rate/rate.less
> +    &--sr-only {
是的，建议抽象一下，以便复用

2023-02-17 01:15 UTC, syxysszyw commented
预览1

2023-02-17 02:16 UTC, byq1213 commented on src/rate/rate.wxml
> +    aria-valuemin="{{0}}"
我看默认value是0 😢 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/18624598/219532418-dde776a7-880d-4078-89b6-c481ddfff0f1.png">

2023-02-17 07:13 UTC, syxysszyw commented on src/rate/rate.wxml
> +    aria-valuemin="{{0}}"
1

2023-02-17 09:10 UTC, syxysszyw commented on src/rate/rate.wxml
> +      <t-icon
为什么要在 t-icon 外面包一层 view 呀？这个变更是为了达成什么效果？

2023-02-17 09:10 UTC, syxysszyw commented on src/rate/rate.wxml
> +    >{{utils.getText(texts,value,defaultTexts)}}{{allowHalf?value+'星':''}}</text
`utils.getText(texts,value,defaultTexts)}}{{allowHalf?value+'星':''` 加上适当的空格？并且在`}}{{`中间加一个“，”试试

2023-02-23 03:27 UTC, LeeJim requested changes

2023-02-23 03:27 UTC, LeeJim commented on src/rate/rate.wxml
> +    >{{utils.getText(texts,value,defaultTexts)}}{{allowHalf?value+'星':''}}</text
已和 @syxysszyw 沟通，可以移除了 `{{allowHalf?value+'星':''}}`

2023-02-23 07:27 UTC, syxysszyw commented
预览1

2023-02-23 07:36 UTC, syxysszyw commented
评分组件格式如下：
★★★★★   文案(可选）

2023-02-23 08:03 UTC, syxysszyw commented
评分组件格式如下：
```
★★★★★    文案(可选）
```
调整评分时星星顶部会有一个小Tips，显示格式为“上面一个★下面一个数字（1-5）”

目前评分组件设置角色为Slider，用户可以通过左右滑动调整评分数值，存在一个小问题：
情况1：右侧文案不显示——（视频定位00：43）目前播报效果分别是'极差', '失望', '一般', '满意', '惊喜'，但顶部Tips（明眼人看到的是）是1-5，视障人士听到的跟明眼人看到的对不上，建议播报内容与明眼人看到的对齐，改为'1星', '2星, '3星', '4星', '5星'或'1星，极差', '2星,失望 '3星，一般', '4星，满意', '5星，惊喜'
情况2：右侧文案有显示——播报的内容应该与右侧文案保持一致

## 其他情况
1、可选半星示例——目前半星和全星（如0.5和1，1.5和2）播报内容相同，无法区分
2、视频定位 01：00 最底部“04 特殊场景”那个示例，明眼人看到的是'非常糟糕', '有些糟糕', '可以尝试', '可以前往', '推荐前往'，但播报效果是'极差', '失望', '一般', '满意', '惊喜'，不符合预期
3、安卓手机上（视频定位  00：32），声明为Slider会读出类似“60%”这样的文案，且由于评分组件在手机上可显示的整体宽度通常比较窄（占据屏幕宽度不到一半，特别是支持选择半星的实际上可调档位会是10个），用户很细微的物理位置变化就会导致评分改变，内容一直在变更，播报的内容也很频繁发生变化，用户可能很难区分当前的调整值

https://user-images.githubusercontent.com/4988284/220851247-6229b017-5d10-4889-bdfb-7353feba67bd.mp4

2023-03-31 07:07 UTC, byq1213 commented
> 

【腾讯 CoDesign】TD-微信小程序-Rate-iOS-03...
https://codesign.qq.com/s/wKrMZexO6B0k1md

2023-04-06 06:27 UTC, syxysszyw commented
预览1

2023-04-06 07:00 UTC, syxysszyw commented on src/rate/rate.wxml
> +    >{{value+'星'}} {{utils.getText(texts,value,defaultTexts)}}</text
这么写可能会有局限性？图标不一定是“星星”

2023-04-07 10:30 UTC, syxysszyw commented
预览1

2023-04-18 02:27 UTC, LeeJim approved these changes

2023-04-18 02:27 UTC, LeeJim commented on src/rate/rate.wxml
> +    >{{value+'星'}} {{utils.getText(texts,value,defaultTexts)}}</text
这个暂时没有更好的答案，就先忽略咯

2023-04-18 02:28 UTC, merged