refactor: support class
Tencent/tdesign-miniprogram pull request #1587
Opened 2023-02-13 09:12 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- refactor: 给所有组件的 externalClasses 属性新增 class

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-02-13 12:01 UTC, LeeJim commented
需要测试一下，是否全部组件正常使用 class

2023-02-15 06:58 UTC, anlyyao commented
@LeeJim  已补充组件快照，通过快照判断是否在每个组件最外层元素class上补充‘class’类名。

ci会挂的原因是 npm run test 会分别执行virtualHost关闭和开启两种情况，两者产生的快照有差异，但快照名称一样，存放位置都在默认__snapshots__文件夹下，因此会冲突，需要merge 处理  #1566 。

2023-02-16 06:14 UTC, anlyyao commented
@LeeJim  已处理

2023-02-16 06:56 UTC, LeeJim requested changes

2023-02-16 06:56 UTC, LeeJim commented on src/calendar/template.wxml
> +<view class="{{_.cls(classPrefix, [['popup', usePopup]])}} class" style="{{_._style([style, customStyle])}}">
需要补一下 t-class

2023-02-16 06:56 UTC, LeeJim commented on src/dialog/dialog.wxml
> +  class="class"
class不应该放在这里，应该和 t-class 同个地方

2023-02-16 06:56 UTC, LeeJim commented on src/divider/divider.wxml
> +<view class="class {{layout==='vertical'? classPrefix + '--vertical-center' : ''}}">
将 t-class 的位置也改到这里来吧

2023-02-16 06:56 UTC, LeeJim commented on src/drawer/drawer.wxml
> +  class="class"
后面用到 popup 的组件，class的位置都需要改一下，放在和 t-class 同个位置

2023-02-16 06:56 UTC, LeeJim commented on src/footer/footer.wxml
> +<view style="{{_._style([style, customStyle])}}" class="{{classPrefix}} class ">
补充支持一下 t-class

2023-02-16 06:56 UTC, LeeJim commented on src/overlay/overlay.wxml
> +  class="{{prefix}}-overlay {{transitionClass}} class"
支持一下 t-class

2023-02-16 06:56 UTC, LeeJim commented on src/picker/picker.wxml
> +<t-popup class="class" visible="{{visible}}" placement="bottom" bind:visible-change="onPopupChange">
位置需要调整

2023-02-16 06:56 UTC, LeeJim commented on src/progress/progress.wxml
> +<view style="{{_._style([style, customStyle])}}" class="{{classPrefix}} class">
支持一下 t-class

2023-02-16 06:56 UTC, LeeJim commented on src/rate/rate.wxml
> +<view class="{{classPrefix}} class" style="{{_._style([style, customStyle])}}">
和 t-class 不是同个位置

2023-02-16 06:56 UTC, LeeJim commented on src/skeleton/skeleton.wxml
> +<view wx:else class="class {{classPrefix}}__content">
这个如果需要加在这里的话，t-class也要加在这里

2023-02-16 06:56 UTC, LeeJim commented on src/swiper-nav/swiper-nav.wxml
> +<view wx:if="{{showControls}}" class="class {{classPrefix}}__btn" style="{{_._style([style, customStyle])}}">
这里需要添加的话，t-class也要补充

2023-02-16 06:56 UTC, LeeJim commented on src/tab-bar-item/tab-bar-item.wxml
> +  class="{{_.cls(classPrefix, [['split', split], ['text-only', !icon], ['crowded', crowded], shape])}} class"
补充 t-class

2023-02-16 06:56 UTC, LeeJim commented on src/tab-panel/tab-panel.wxml
> +  class="class {{classPrefix}} {{active ? prefix + '-is-active': ''}}"
补充 t-class

2023-02-16 06:56 UTC, LeeJim commented on src/transition/transition.wxml
> +  class="class {{classPrefix}} {{ transitionClass }}"
补充 t-class

2023-02-16 06:56 UTC, LeeJim commented on src/tree-select/tree-select.wxml
> +<view class="{{classPrefix}} class" style="{{_._style(['height:' + _.addUnit(height) , style, customStyle])}}">
补充 t-class

2023-02-16 08:54 UTC, anlyyao commented
@LeeJim 已补充支持 t-class。 原t-class位置暂时未做调整，原因是多个组件（upload、tree-select、swiper等存在嵌套组件）在实现过程中用到了t-class，一旦调整，需要一并处理，并在原t-class位置提供一个新的外部样式类名。

2023-02-16 09:10 UTC, anlyyao commented
@LeeJim  cr 问题已处理。 divider组件t-class位置调整到根节点，窗体类组件未动。

2023-02-16 13:28 UTC, LeeJim approved these changes

2023-02-16 13:28 UTC, LeeJim commented on src/dialog/dialog.wxml
> +  class="class"
经讨论，暂不修改

2023-02-16 13:47 UTC, merged