chore(Message): remove action and add the link attribute
Tencent/tdesign-miniprogram pull request #1637
Opened 2023-02-22 03:53 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- break(Message): 移除 `action` 属性相关
- feat(Message): 新增 `link` 属性
- fix(Message): 修复主题图标不正确

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-02-22 06:57 UTC, LeeJim requested changes

2023-02-22 06:57 UTC, LeeJim commented on src/message/message.ts
> +      this.setData({
优化下写法：`this.setData({ _link })`

2023-02-22 06:57 UTC, LeeJim commented on src/message/message.wxml
> +      prefixIcon="{{_link.prefixIcon}}"
补充默认值，下面几个属性也是

2023-02-22 08:32 UTC, anlyyao commented on src/message/message.ts
> +      this.setData({
1

2023-02-22 08:32 UTC, anlyyao commented on src/message/message.wxml
> +      prefixIcon="{{_link.prefixIcon}}"
1

2023-02-23 04:46 UTC, LeeJim approved these changes

2023-02-23 04:47 UTC, merged