chore(NoticeBar): extra attribute is renamed to operation
Tencent/tdesign-miniprogram pull request #1638
Opened 2023-02-22 08:01 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- break(NoticeBar):  `extra` 属性更名为 `operation`
- fix(NoticeBar): 修复主题图标不正确

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-02-23 04:50 UTC, LeeJim requested changes

2023-02-23 04:50 UTC, LeeJim commented on src/notice-bar/notice-bar.wxml
> +  <view class="{{classPrefix}}__content-wrap">
这里的事件不应该移除

2023-02-23 04:50 UTC, LeeJim commented on src/notice-bar/notice-bar.wxml
> +      <view class="{{classPrefix}}__operation {{prefix}}-class-operation" bind:tap="clickOperation">
配合外面的事件，这里用 catch 会合理一些

2023-02-23 09:43 UTC, anlyyao commented on src/notice-bar/notice-bar.wxml
> +      <view class="{{classPrefix}}__operation {{prefix}}-class-operation" bind:tap="clickOperation">
1

2023-02-23 09:43 UTC, anlyyao commented on src/notice-bar/notice-bar.wxml
> +  <view class="{{classPrefix}}__content-wrap">
已补充

2023-02-27 15:01 UTC, LeeJim approved these changes

2023-02-27 15:01 UTC, merged