chore(ImageViewer): remove backgroundColor attribute
Tencent/tdesign-miniprogram pull request #1656
Opened 2023-02-24 10:34 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- break(ImageViewer): 移除 backgroundColor 属性
- feat(ImageViewer): 新增 --td-image-viewer-mask-bg-color 用于修改遮罩层颜色
- fix(ImageViewer): 修复图片显示不全的问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-02-27 15:06 UTC, LeeJim requested changes

2023-02-27 15:06 UTC, LeeJim commented on src/image-viewer/image-viewer.ts
> +      const originSwiperStyle = this.data.swiperStyle;
这个 swiperStyle 在哪里会赋值？，上面的 imageStyle 同理

2023-02-27 15:23 UTC, anlyyao commented on src/image-viewer/image-viewer.less
> +@image-viewer-mask-bg-color: var(--td-image-viewer-mask-bg-color, rgba(0, 0, 0, 1));
1

2023-02-27 15:24 UTC, anlyyao commented on src/image-viewer/image-viewer.ts
> +      const originSwiperStyle = this.data.swiperStyle;
每次加载一张图片，imagesStyle，swiperStyle都会分别记录图片的宽高信息、

2023-02-27 15:26 UTC, LeeJim approved these changes

2023-03-07 09:22 UTC, LeeJim approved these changes

2023-03-07 14:40 UTC, merged