fix(Button): fix disabled invalid
Tencent/tdesign-miniprogram pull request #1739
Opened 2023-03-07 11:45 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
fix #1689 

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(Button): 修复 `disabled` 态下事件未禁用问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-03-07 14:48 UTC, LeeJim requested changes

2023-03-07 14:48 UTC, LeeJim commented on src/button/button.wxml
> +  open-type="{{disabled || loading || openType}}"
这里为啥这么改？预期是字符串的，这里改成了 boolean 和 opentype

2023-03-09 02:24 UTC, anlyyao commented on src/button/button.wxml
> +  open-type="{{disabled || loading || openType}}"
已改为 `open-type="{{disabled || loading ? '' : openType}}"`

2023-03-13 02:53 UTC, LeeJim approved these changes

2023-03-13 03:15 UTC, merged