feet(swiper): css starndard
Tencent/tdesign-miniprogram pull request #19
Opened 2021-12-20 07:46 UTC by jin0209

2021-12-21 09:20 UTC, LeeJim requested changes
`t-`  开头的地方都用下 prefix 配置吧。

2021-12-21 09:20 UTC, LeeJim commented on src/swiper/swiper-nav.less
> +      &.t-is-active {
这里也要用下 prefix

2021-12-21 09:20 UTC, LeeJim commented on src/swiper/swiper-nav.less
> +      &.t-is-active {
这里也要用下 prefix

2021-12-22 09:15 UTC, jin0209 commented on src/swiper/swiper-nav.less
> +      &.t-is-active {
ok

2021-12-22 09:15 UTC, jin0209 commented on src/swiper/swiper-nav.less
> +      &.t-is-active {
ok

2021-12-24 06:57 UTC, JJunYang requested changes

2021-12-24 06:57 UTC, JJunYang commented on src/swiper/swiper-nav.wxml
> +  class="t-class {{classPrefix}} {{classPrefix}}--{{direction}}"
t用prefix替代

2021-12-26 02:34 UTC, LeeJim commented
externalClasses optinos 的 t-class 记得也改成 prefix

2021-12-27 08:51 UTC, LeeJim approved these changes
LGTM

2021-12-27 08:52 UTC, merged