feat: upload组件新增事件select-change
Tencent/tdesign-miniprogram pull request #194
Opened 2022-02-23 11:04 UTC by Winfans

2022-02-24 07:21 UTC, LeeJim requested changes

2022-02-24 07:21 UTC, LeeJim commented on src/upload/props.ts
> +    type: Array,
这个地方小程序需要特殊处理，不能修改

2022-02-24 07:21 UTC, LeeJim commented on src/upload/type.ts
> +  column?: number;
这里格式化有问题

2022-02-25 07:32 UTC, jin0209 approved these changes
lgtm

2022-02-25 07:34 UTC, lixingdecai approved these changes
LGTM

2022-02-25 08:03 UTC, LeeJim commented on src/upload/upload.ts
> +          currentSelectedFiles: [files]
这里的字段名改成 files 吧，这样和其他比较一致。

2022-02-25 08:03 UTC, LeeJim commented on src/upload/upload.ts
> +          currentSelectedFiles: [files]
同样

2022-02-25 13:35 UTC, LeeJim approved these changes
LGTM

2022-02-25 13:35 UTC, merged