fix(dialog): display of cancel and confirm button when calling a command.
Tencent/tdesign-miniprogram pull request #1986
Opened 2023-05-11 05:44 UTC by yuchumian

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(dialog): 使用命令调用时，第一次调用显示所有按钮，当再次调用时把confirmBtn设置为null或者confirmBtn、cancelBtn两者都设置为null，此时还是显示所有按钮

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-05-12 02:40 UTC, LeeJim requested changes
_cancel是通过 cancelBtn 计算得出，不能这样简单的修改

2023-05-12 03:06 UTC, yuchumian commented
> _cancel是通过 cancelBtn 计算得出，不能这样简单的修改

``` 

Object.keys(buttonMap).forEach((key) => {
        const btn = buttonMap[key];
        const base: Record<string, any> = {
          block: true,
          class: [...cls, `${classPrefix}__button--${key}`],
          externalClass: [...externalCls, `${prefix}-class-${key}`],
          variant: rect.buttonVariant,
        };

        if (key === 'cancel' && rect.buttonVariant === 'base') {
          base.theme = 'light';
        }

        if (typeof btn === 'string') {
          rect[`_${key}`] = { ...base, content: btn };
        } else if (btn && typeof btn === 'object') {
          rect[`_${key}`] = { ...base, ...btn };
        }
      });

```
这块吗？ 当btn为空的时候这里并没有做处理

2023-05-12 03:09 UTC, yuchumian commented
![image](https://github.com/Tencent/tdesign-miniprogram/assets/26185330/9a87ab3c-6da1-486f-ae57-9591a5679a58)

2023-05-15 06:27 UTC, LeeJim commented
嗯，所以基于这个基础上处理

2023-05-15 07:48 UTC, yuchumian commented
> 嗯，所以基于这个基础上处理
 我现在把它给置空了
`rect[`_${key}`] = null;`

2023-05-15 10:33 UTC, LeeJim approved these changes

2023-05-15 10:36 UTC, merged