feet(skeleton): css starndard
Tencent/tdesign-miniprogram pull request #20
Opened 2021-12-20 07:56 UTC by jin0209

2021-12-21 09:27 UTC, LeeJim requested changes

2021-12-21 09:27 UTC, LeeJim commented on src/skeleton/skeleton.wxml
> +  class="t-class {{classPrefix}} {{ animation ? classPrefix + '__animate-' + animation : '' }}"
感觉 animate 应该属于 modifier？
所以应该是 `--animate` ?

2021-12-22 09:08 UTC, jin0209 commented on src/skeleton/skeleton.wxml
> +  class="t-class {{classPrefix}} {{ animation ? classPrefix + '__animate-' + animation : '' }}"
OK

2021-12-23 06:32 UTC, LeeJim approved these changes
LGTM

2021-12-23 06:32 UTC, merged