fix(indexes): 索引导航无法选中问题
Tencent/tdesign-miniprogram pull request #2036
Opened 2023-05-25 05:02 UTC by lolhezihehe

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
fix #1469 
fix #1605 

### 💡 需求背景和解决方案
在ready之后的数据未重新计算高度，导致导航无法选中；
如果是异步数据则不需要组件自动加载索引字符，增加async字段判断；

### 📝 更新日志

- fix(indexes): 索引导航无法选中问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-05-30 03:21 UTC, LeeJim requested changes
我看了下，这个 PR 解决两个问题：
1. 异步传入数据时，默认渲染了错误的index-list，由此引入了新属性 async，在我看来这个是可以省略的，可以判断传入的 index-list 是否为 undefined ，是的话才默认渲染，为空数组的话，则不渲染即可。（另外，这里需要将 index-list 的 type 改成 null，否则 value 就算是undefined也会被转换成对应 type 的类型）
2. 解决无法选择的问题，这个是OK的。

2023-05-31 05:23 UTC, lolhezihehe commented
> 异步传入数据时，默认渲染了错误的index-list，由此引入了新属性 async，在我看来这个是可以省略的，可以判断传入的 index-list 是否为 undefined ，是的话才默认渲染，为空数组的话，则不渲染即可。（另外，这里需要将 index-list 的 type 改成 null，否则 value 就算是undefined也会被转换成对应 type 的类型）
原本想通过undefined判断，不清楚小程序为什么要重置默认值，默认值null确实可以解决

2023-06-01 06:43 UTC, LeeJim requested changes

2023-06-01 06:43 UTC, LeeJim commented on src/indexes/props.ts
> +    value: null,
这样默认值是会转成空数组的，需要将 type 改成 null 才行

2023-06-01 11:47 UTC, merged