fix(Fab): resolved hover-class invalid
Tencent/tdesign-miniprogram pull request #2093
Opened 2023-06-13 16:05 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(Fab): 修复 `buttonProps` 中的 `hoverClass`属性透传至 `button` 无效

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-06-14 09:10 UTC, LeeJim requested changes

2023-06-14 09:10 UTC, LeeJim commented on src/common/template/button.wxml
> +    hover-class="{{disabled || loading ? '' : (hoverClass || prefix + '-button--hover')}}"
这里的 ` || prefix + '-button--hover' ` 是冗余的

2023-06-14 14:30 UTC, anlyyao commented on src/common/template/button.wxml
> +    hover-class="{{disabled || loading ? '' : (hoverClass || prefix + '-button--hover')}}"
已处理

2023-06-20 06:47 UTC, LeeJim approved these changes

2023-06-20 06:47 UTC, merged