fix(button): 修复round无效,支持icon按钮.shape支持rectangle(默认)、square、round、circle
Tencent/tdesign-miniprogram pull request #212
Opened 2022-03-04 04:02 UTC by anlyyao

修改：
1. shape支持4种：长方形rectangle(默认)、正方形square、圆角长方形round、圆形circle。
shape默认retangel，所有形式都有默认圆角8rpx， 如果需要去掉圆角，可使用外部样式t-class去除。
2. 关于icon和文本之间的距离，三种实现方式。(a.外部样式t-class-icon，给icon右边margin；b.使用slot插槽；c.使用props.content添加文本)

2022-03-04 07:53 UTC, LeeJim requested changes
要记得同步修改文档

2022-03-04 07:53 UTC, LeeJim commented on example/pages/button/button.wxml
> +      <t-button t-class="no-border-radius" size="large" block>次按钮</t-button>
视觉上这个应该是无边框的

2022-03-04 07:53 UTC, LeeJim commented on src/button/button.less
> +  &--rectangle {
没用就删除了

2022-03-04 07:53 UTC, LeeJim commented on src/button/button.less
> +        border-radius: (@button-large-height / 2);
这个设置50%就行了

2022-03-04 07:53 UTC, LeeJim commented on src/button/button.ts
> +        classList.push(`${name}--icon`);
icon-only 会不会好一些？

2022-03-04 08:35 UTC, anlyyao commented on src/button/button.ts
> +        classList.push(`${name}--icon`);
OK

2022-03-04 08:35 UTC, anlyyao commented on src/button/button.less
> +        border-radius: (@button-large-height / 2);
OK

2022-03-04 08:35 UTC, anlyyao commented on src/button/button.less
> +  &--rectangle {
已删除

2022-03-04 08:35 UTC, anlyyao commented on src/button/button.ts
> +        classList.push(`${name}--icon`);
忘记删除了，实际未用

2022-03-04 08:36 UTC, anlyyao commented on example/pages/button/button.wxml
> +      <t-button t-class="no-border-radius" size="large" block>次按钮</t-button>
已对齐视觉稿

2022-03-04 09:57 UTC, LeeJim requested changes

2022-03-04 09:57 UTC, LeeJim commented on src/button/README.md
> +| shape                  | String      | rectangle    | 按钮形状，有4种：长方形/正方形/圆角长方形/圆形。可选项：rectangle/square/round/ircle| N    |
一行错了两个单词：rectangle, circle

2022-03-04 09:57 UTC, LeeJim commented on src/button/README.md
> +shape默认retangel
单词错了，rectangle

2022-03-04 09:57 UTC, LeeJim commented on example/pages/button/button.wxml
> +      <t-button t-class="no-border-radius no-border" size="large" block>次按钮</t-button>
这个是不是应该使用shape=rectangle，而不是no-border-radius来处理

2022-03-04 09:57 UTC, LeeJim commented on src/button/button.less
> +@button-padding-horizontal-default: 12px;
default 改成 m 会合理一些吧。其他的地方也记得改下

2022-03-07 03:49 UTC, LeeJim approved these changes

2022-03-07 07:29 UTC, merged