feat(search): support maxcharacter and maxlength property
Tencent/tdesign-miniprogram pull request #2229
Opened 2023-07-28 02:54 UTC by betavs

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
- fix #2228 

### 💡 需求背景和解决方案
无

### 📝 更新日志

- feat(search): 新增 ```maxcharacter``` 和 ```maxlength``` 属性

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-08-01 14:03 UTC, LeeJim commented
支持 inputProps 透传 input 的所有属性会更好

2023-08-03 02:57 UTC, LeeJim requested changes

2023-08-03 02:57 UTC, LeeJim commented on src/search/search.ts
> +    this.setData({ value: realValue || value });
realValue 的默认值等于 value，就可以省略`|| value`

2023-08-03 02:57 UTC, LeeJim commented on src/search/search.ts
> +    if (maxcharacter && typeof maxcharacter === 'number') {
这里需要判断下 maxcharacter 是否大于 0

2023-08-03 03:10 UTC, betavs commented on src/search/search.ts
> +    this.setData({ value: realValue || value });
```
  onInput(e) {
    let { value } = e.detail;
    const { maxcharacter } = this.properties;

    if (maxcharacter && typeof maxcharacter === 'number' && maxcharacter > 0) {
      const { characters } = getCharacterLength('maxcharacter', value, Number(maxcharacter));

      value = characters;
    }

    this.setData({ value });
    this.triggerEvent('change', { value });
  }
```

2023-08-06 01:24 UTC, LeeJim requested changes

2023-08-06 01:24 UTC, LeeJim commented on src/search/search.ts
> +      const { characters } = getCharacterLength('maxcharacter', value, Number(maxcharacter));
if 里已经判断了 maxcharacter 的 type 是 number，里面就不需要转换类型了

2023-08-07 07:25 UTC, LeeJim commented
以后不要把分支名取得这么范，很容易和其他分支冲突
<img width="478" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/7017290/906bc16d-a2a1-4f38-b703-670d23ee3aaa">

2023-08-07 08:11 UTC, LeeJim approved these changes

2023-08-07 08:11 UTC, merged