feat(loading): add css variable for text color
Tencent/tdesign-miniprogram pull request #2273
Opened 2023-08-12 08:52 UTC by ElanYoung

BREAKING CHANGE: q

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

新增 CSS Variable

### 📝 更新日志

- feat(Loading): 新增 CSS Variable 用于调整加载提示文案颜色

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-08-15 09:02 UTC, LeeJim requested changes
color 的默认值改成 inherit 比较合理

2023-08-15 09:46 UTC, ElanYoung commented
> color 的默认值改成 inherit 比较合理

这样改行嘛 @loading-text-color: var(--td-loading-text-color, inherit);

2023-08-15 10:20 UTC, LeeJim commented
> > color 的默认值改成 inherit 比较合理
> 
> 这样改行嘛 @loading-text-color: var(--td-loading-text-color, inherit);

是这个意思，记得改下 md

2023-08-15 12:27 UTC, ElanYoung commented
> > > color 的默认值改成 inherit 比较合理
> > 
> > 
> > 这样改行嘛 @loading-text-color: var(--td-loading-text-color, inherit);
> 
> 是这个意思，记得改下 md

改完啦

2023-08-16 01:18 UTC, LeeJim approved these changes

2023-08-16 01:18 UTC, merged