fix(side-bar): example abnormal
Tencent/tdesign-miniprogram pull request #2325
Opened 2023-08-28 06:42 UTC by betavs

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

- fix #2323 

### 💡 需求背景和解决方案

无

### 📝 更新日志

- fix(SideBar): 示例异常

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-08-28 09:22 UTC, LeeJim requested changes

2023-08-28 09:22 UTC, LeeJim commented on src/dropdown-menu/__test__/index.test.js
> +    // expect(comp.toJSON()).toMatchSnapshot();
这里为啥注释了？

2023-08-28 09:24 UTC, betavs commented on src/dropdown-menu/__test__/index.test.js
> +    // expect(comp.toJSON()).toMatchSnapshot();
单元测试有问题

2023-08-29 06:59 UTC, LeeJim commented on src/dropdown-menu/__test__/index.test.js
> +    // expect(comp.toJSON()).toMatchSnapshot();
我来处理

2023-08-29 11:13 UTC, merged