feat(notice-bar): enable event change
Tencent/tdesign-miniprogram pull request #2373
Opened 2023-09-21 04:31 UTC by betavs

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

fix #2370 

### 💡 需求背景和解决方案

### 📝 更新日志

- feat(NoticeBar): 新增 `change` 事件

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-09-21 07:32 UTC, LeeJim requested changes

2023-09-21 07:32 UTC, LeeJim commented on src/notice-bar/README.md
> +change | `(current: number, source: SwiperChangeSource)` | 当 `direction="vertical"` 时轮播切换时触发。[详细类型定义](https://github.com/Tencent/tdesign-miniprogram/tree/develop/src/swiper/type.ts)。<br/>`type Swiper
这个描述错了，change的事情返回参数有 current、source

2023-09-25 06:36 UTC, LeeJim requested changes

2023-09-25 06:36 UTC, LeeJim commented on src/notice-bar/README.en-US.md
> +change | `(current: number, source: '' \| 'autoplay' \| 'touch', currentItemId: string)` | `direction="vertical"`
currentItemId 是哪来的？

2023-09-25 06:44 UTC, betavs commented on src/notice-bar/README.en-US.md
> +change | `(current: number, source: '' \| 'autoplay' \| 'touch', currentItemId: string)` | `direction="vertical"`
> currentItemId 是哪来的？

![image](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/1dfc3aa7-7a53-4885-9ab4-18e95fce9800)

2023-11-01 03:45 UTC, anlyyao commented on src/notice-bar/README.md
> +change | `(current: number, source: '' \| 'autoplay' \| 'touch', currentItemId: string)` | 当 `direction="vertical"` 时轮播切换时触发
source 应该只有 autoplay和touch两种情况，不存在空字符。 currentItemId感觉可以过滤掉，因为我们组件内部SwiperItem上没有设置ItemId，这里即使返回了也都是空字符，没有意义～

2023-11-01 04:00 UTC, betavs commented on src/notice-bar/README.md
> +change | `(current: number, source: '' \| 'autoplay' \| 'touch', currentItemId: string)` | 当 `direction="vertical"` 时轮播切换时触发
![image](https://github.com/Tencent/tdesign-miniprogram/assets/34408516/583e4a4a-dbcd-4479-b6e9-2694497af0e4)

2023-11-01 04:05 UTC, anlyyao approved these changes

2023-11-01 04:14 UTC, anlyyao approved these changes

2023-11-01 04:16 UTC, anlyyao approved these changes

2023-11-22 03:30 UTC, anlyyao commented
@LeeJim  leejim 抽空再看看这里哦～，我这边没问题了

2023-12-14 04:00 UTC, closed without merging