fix(inputMaxCount): 解决设置最大长度时类型为number、digit不生效问题
Tencent/tdesign-miniprogram pull request #2497
Opened 2023-12-14 12:55 UTC by zyqq

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

- https://github.com/Tencent/tdesign-miniprogram/issues/2103
- https://github.com/Tencent/tdesign-miniprogram/pull/2108
- https://github.com/Tencent/tdesign-miniprogram/issues/2368

### 💡 需求背景和解决方案

- 需求背景

之前的历史问题（https://github.com/Tencent/tdesign-miniprogram/issues/2103、https://github.com/Tencent/tdesign-miniprogram/pull/2108）的处理方式有误,导致出现了新的问题：https://github.com/Tencent/tdesign-miniprogram/issues/2368

- 解决方案

1、历史问题主要是null、undefined没有===严格判断，而是采用==和!等去判断空值，导致把0算进去了。因此用value !== null && value !== undefined 改成严格判断
2、去掉排除类型对长度设置的条件限制。

- 自测示例
<img width="1637" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/15664576/6220b1ca-dad1-4cd5-9314-88f1e48f4a4e">

### 📝 更新日志

1. fix(input): 输入框设置maxlength和maxcharacter在type为digit、number时无效问题修复

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-12-15 02:58 UTC, betavs commented on src/input/input.ts
> +      this.updateValue(value !== null && value !== undefined ? value : '');
```typescript
this.updateValue(value ?? '');
```
这里可以优化一下

2023-12-15 03:10 UTC, zyqq commented on src/input/input.ts
> +      this.updateValue(value !== null && value !== undefined ? value : '');
<img width="203" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/15664576/de38a75c-5c79-4988-854e-34c79a96d05d">
可以的，双问号比三元表达式好，更适合判断值不存在时的情况

2023-12-15 03:40 UTC, zyqq commented on src/common/utils.ts
> +export const isNullOrUndefined = (value: any): boolean => isNull(value) || isUndefined(value);
参考@sindresorhus/is源码增加此工具函数，LGTM

2023-12-15 04:08 UTC, betavs commented on src/common/utils.ts
> +export const isNullOrUndefined = (value: any): boolean => isNull(value) || isUndefined(value);
定义`isOfType`函数后延伸出一个问题，之前判断`isBool`等函数是否也要调整呢🤔

2023-12-15 06:39 UTC, zyqq commented on src/common/utils.ts
> +export const isNullOrUndefined = (value: any): boolean => isNull(value) || isUndefined(value);
<img width="432" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/15664576/9d87f6ba-c350-4dc0-ad90-f74158947a88">
<img width="605" alt="image" src="https://github.com/Tencent/tdesign-miniprogram/assets/15664576/bcc8af8d-813c-4096-a61b-c2d76ad2b7dc">
看之前也有许多不规范的，定义了工具函数没有用。像只判断了typeof sizeLimit === 'number'这里NaN也会判断为number。

应该另开一个issue统一重构优化。

2023-12-15 06:58 UTC, betavs commented on src/common/utils.ts
> +export const isNullOrUndefined = (value: any): boolean => isNull(value) || isUndefined(value);
所以，这里我建议还是不用定义`isOfType`函数来处理的

2023-12-19 02:55 UTC, betavs requested changes

2023-12-19 02:55 UTC, betavs commented on src/common/utils.ts
> +export const isNullOrUndefined = (value: any): boolean => isNull(value) || isUndefined(value);
建议单独提交一个PR来优化

2023-12-19 02:55 UTC, betavs commented on src/common/utils.ts
> +export const isNullOrUndefined = (value: any): boolean => isNull(value) || isUndefined(value);
https://github.com/Tencent/tdesign-miniprogram/blob/9e4e823dbd7a609697eea97584d84f3d9737c86d/src/common/utils.ts#L113

```typescript
export const isDef = function (value: any): boolean {
```

建议将`isDef`导出，将在`input`中使用

2023-12-19 02:55 UTC, betavs commented on src/common/utils.ts
> +  if (isNullOrUndefined(str) || str.length === 0) {
可以不用调整

2023-12-19 02:55 UTC, betavs commented on src/input/input.ts
> +import { getCharacterLength, calcIcon, isNullOrUndefined } from '../common/utils';
```typescript
import { getCharacterLength, calcIcon, isDef } from '../common/utils';
```

2023-12-19 02:55 UTC, betavs commented on src/input/input.ts
> +          count: !isNullOrUndefined(value) ? String(value).length : 0,
```typescript
count: isDef(value) ? String(value).length : 0,
```

2023-12-19 03:35 UTC, zyqq commented on src/common/utils.ts
> +  if (isNullOrUndefined(str) || str.length === 0) {
需要调整，因为这里会把0误认为不存在，导致此问题：https://github.com/Tencent/tdesign-miniprogram/issues/2103

2023-12-19 03:43 UTC, betavs commented on src/common/utils.ts
> +  if (isNullOrUndefined(str) || str.length === 0) {
那可以用 `isDef` 来处理

2023-12-20 08:12 UTC, betavs approved these changes

2023-12-20 08:28 UTC, merged