feat(search): 新增自动完成项预览列表. (#2432)
Tencent/tdesign-miniprogram pull request #2520
Opened 2023-12-27 03:18 UTC by byq1213

fix #2432

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

#2432 

### 💡 需求背景和解决方案

### 📝 更新日志

- feat(search): 新增自动完成项预览列表. (#2432)
- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-12-27 13:50 UTC, jarmywang requested changes
1、search.wxml中key不对
2、type.ts中缺少注释
3、预览列表建议增加点击效果以及点击后收起
4、新增的属性与事件要补充到readme
5、建议item的字体、颜色增加css变量

2023-12-27 13:52 UTC, jarmywang commented
<img width="335" alt="企业微信截图_617bfb6e-c1e3-4687-82ca-56a77fc443df" src="https://github.com/Tencent/tdesign-miniprogram/assets/8576654/fe75fcf8-fb94-46b2-8c8f-9c75bf256374">
@Wen1kang 麻烦设计师看一下默认样式

2024-02-04 03:14 UTC, RADWIMPS426 commented
@Wen1kang

2024-03-07 02:38 UTC, RADWIMPS426 commented
> <img alt="企业微信截图_617bfb6e-c1e3-4687-82ca-56a77fc443df" width="335" src="https://private-user-images.githubusercontent.com/8576654/293042856-fe75fcf8-fb94-46b2-8c8f-9c75bf256374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzkzMjYsIm5iZiI6MTcwOTc3OTAyNiwicGF0aCI6Ii84NTc2NjU0LzI5MzA0Mjg1Ni1mZTc1ZmNmOC1mYjk0LTQ2YjItOGM4Zi05Yzc1YmYyNTYzNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDIzNzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQzYmNlZjM0ZDZiNjlkN2IxNGJkYTkxYThhMWQ3MDc3ZWNmYzRjZjBkYjQyZjE1ZDA4ZjkxZDYwNzE5MjJlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vpP0FL-xhpgbadCgr4FdSSFrniYUAdGHjT25Zf71bn0"> @RADWIMPS426 麻烦设计师看一下样式及交互

<img width="770" alt="企业微信截图_c2208765-9db6-4dc2-af64-8c1287d349a3" src="https://github.com/Tencent/tdesign-miniprogram/assets/124988288/e9dab3d3-dae9-46c6-a20c-4debeba72c7b">

### 1.联想结果应该是要左对齐分割线

### 2.联想关联字符颜色要高亮才行

### 3.现在不知道这个单元格的高度，需要二次确认

2024-06-27 11:34 UTC, anlyyao approved these changes

2024-06-27 11:48 UTC, anlyyao commented
> 1、search.wxml中key不对 2、type.ts中缺少注释 3、预览列表建议增加点击效果以及点击后收起 4、新增的属性与事件要补充到readme 5、建议item的字体、颜色增加css变量

API工具导出小程序端的文件有点问题，稍后处理，先手动补充进md文档

2024-06-27 12:20 UTC, anlyyao commented
https://github.com/TDesignOteam/tdesign-api/pull/314 @jarmywang

2024-06-28 05:20 UTC, jarmywang requested changes
请补充README

2024-07-01 08:13 UTC, jarmywang approved these changes

2024-07-01 08:13 UTC, merged