feat(button): add new prop customDataset
Tencent/tdesign-miniprogram pull request #259
Opened 2022-03-14 07:59 UTC by anlyyao

Button组件prop新增customDataset

2022-03-14 08:28 UTC, LeeJim requested changes

2022-03-14 08:28 UTC, LeeJim commented on src/button/README.md
> +custom-dataset | Object | - | 自定义 dataset，可通过 event.currentTarget.dataset.custom 获取。TS 类型：`any` | N
类型需要调整

2022-03-14 08:59 UTC, LeeJim approved these changes

2022-03-14 08:59 UTC, merged

2023-07-20 07:20 UTC, codeboytj commented
为什么我这边试了一下，这个issue指出的问题现在依然存在啊