perf(steps): update step-status mode && addboundary condition
Tencent/tdesign-miniprogram pull request #307
Opened 2022-03-30 02:51 UTC by anlyyao

- steps
- 更新step状态判断函数
- 新增两种边界条件（1.secondStep存在，子步骤条为default时，其stepItem状态应为process；2.secondStep存在，子步骤条为finish且不为最后一个子步骤时，其stepItem状态应为proces）

2022-03-30 03:20 UTC, LeeJim requested changes

2022-03-30 03:20 UTC, LeeJim commented on src/steps/step-item.ts
> +          item[itemAttr] = judgeStepStatus(index, value, status);
里面只有一行代码的话，可以改成:

`item[itemAttr] = data[attr].map((item, index) => judgeStepStatus(index, value, status))`

2022-03-30 03:20 UTC, LeeJim commented on src/steps/step-item.ts
> +      const isLastChild = (data, index) => {
箭头函数里面只有一行 return 的话，可以改成：

```js
const isLastChild = (data, index) => index == data.length - 1;
```

2022-03-30 03:20 UTC, LeeJim commented on src/steps/step-item.ts
>            secondStep !== undefined &&
这里用 if 比较好

2022-03-30 03:20 UTC, LeeJim commented on src/steps/step-item.ts
> +              currentStatus === 'finish' &&
用 if 比较好

2022-03-30 04:43 UTC, LeeJim requested changes

2022-03-30 04:43 UTC, LeeJim commented on src/steps/step-item.ts
>              judgeObjAttr(this.data, '_subStepItems') &&
这个 && 是多余的吧

2022-03-30 04:43 UTC, LeeJim commented on src/steps/step-item.ts
> +        if (itemIndex > current) return 'default';
最后一个 if 是多余的吧

2022-03-30 04:52 UTC, anlyyao commented on src/steps/step-item.ts
>              judgeObjAttr(this.data, '_subStepItems') &&
不多余吧 、 先判断属性存在，在修改属性状态- -

2022-03-31 06:49 UTC, LeeJim approved these changes

2022-03-31 06:49 UTC, merged