feat(steps): optimize classname and less
Tencent/tdesign-miniprogram pull request #32
Opened 2021-12-21 12:35 UTC by LeeJim

Steps 修改：
- 规范化ClassName，满足 BEM 规范
- 优化less的写法，使用 less variable

2021-12-22 09:04 UTC, jin0209 commented on src/steps/step-item.wxml
> +        <view wx:elif="{{icon}}" class="{{classPrefix}}__icon--number {{classPrefix}}__icon--icon">
为啥这里要2个class?

2021-12-22 09:06 UTC, jin0209 commented on src/steps/styles/_index.less
> +    .@{item}__icon--icon {
.@{item}__icon--number

2021-12-24 02:26 UTC, JJunYang requested changes

2021-12-24 02:26 UTC, JJunYang commented on src/steps/step-item.wxml
> +        <view wx:else class="{{classPrefix}}__icon--number">{{index + 1}}</view>
--number修饰类不能单独使用，此处可改为{{classPrefix}}__icon-number

2021-12-27 07:24 UTC, LeeJim commented on src/steps/step-item.wxml
> +        <view wx:elif="{{icon}}" class="{{classPrefix}}__icon--number {{classPrefix}}__icon--icon">
就是每个 step-item 上面那个点。有可能是 icon ，有可能是 text。
命名确实不好，我看看怎么改下

2021-12-27 07:24 UTC, LeeJim commented on src/steps/styles/_index.less
> +    .@{item}__icon--icon {
这是形容有 icon 的情况。我看看怎么优化下命名吧

2021-12-27 08:32 UTC, LeeJim commented on src/steps/step-item.wxml
> +        <view wx:else class="{{classPrefix}}__icon--number">{{index + 1}}</view>
OK

2021-12-28 03:26 UTC, jin0209 approved these changes
lgtm

2021-12-28 07:42 UTC, JJunYang approved these changes

2021-12-29 03:06 UTC, merged