feat(actionsheet): add actionsheet component
Tencent/tdesign-miniprogram pull request #345
Opened 2022-04-11 15:46 UTC by NuoHui

2022-04-14 07:49 UTC, LeeJim requested changes

2022-04-14 07:49 UTC, LeeJim commented on src/action-sheet/action-sheet.ts
> +  externalClasses = [];
添加下外部样式类，如 t-class

2022-04-14 07:49 UTC, LeeJim commented on src/action-sheet/action-sheet.ts
> +      this.setData({ visible: false });
主要 visible 应该是受控的。
可以参考文档：https://github.com/Tencent/tdesign-miniprogram/wiki/%E5%8F%97%E6%8E%A7%E6%94%B9%E9%80%A0

2022-04-14 07:49 UTC, LeeJim commented on src/action-sheet/action-sheet.wxml
> +        is="grid"
怎么不用 grid 组件？

2022-04-14 07:49 UTC, LeeJim commented on src/action-sheet/template/action-sheet-list.wxml
> +    <t-icon wx:if="{{item.icon}}" name="{{item.icon}}" class="{{classPrefix}}__list-item-icon" size="24px"></t-icon>
最好使用 rpx

2022-04-15 18:00 UTC, NuoHui commented on example/pages/action-sheet/action-sheet.ts
> +            text: '组件引用：列表型',
嗯这里已经改了

2022-04-15 18:01 UTC, NuoHui commented on example/pages/action-sheet/constants.ts
> +      url: 'https://cdn-we-retail.ym.tencent.com/retail-ui/components-exp/avatar/avatar-v2/1.png',
这里去掉了`url`字段，还是用`icon`字段，同时支持图标、`url`格式。

2022-04-15 18:01 UTC, NuoHui commented on src/action-sheet/README.md
> +```
嗯 这里已补充

2022-04-15 18:02 UTC, NuoHui commented on src/action-sheet/action-sheet.ts
> +  externalClasses = [];
嗯 已经添加

2022-04-15 18:02 UTC, NuoHui commented on src/action-sheet/action-sheet.wxml
> +        is="grid"
嗯 之前没注意 已经替换`grid`组件

2022-04-15 18:03 UTC, NuoHui commented on src/action-sheet/template/action-sheet-list.wxml
> +    <t-icon wx:if="{{item.icon}}" name="{{item.icon}}" class="{{classPrefix}}__list-item-icon" size="24px"></t-icon>
嗯 已改

2022-04-15 18:18 UTC, NuoHui commented on src/action-sheet/action-sheet.ts
> +      this.setData({ visible: false });
我个人理解，这里`visible `作为受控的，那么需要对应暴露一个事件，目前我新增了为`visible-change`。
现在内部相关逻辑都用`this._trigger('visible-change', { visible: xxx });`对外由用户控制。

2022-04-18 02:38 UTC, LeeJim commented on src/action-sheet/action-sheet.wxs
> +  console.log(name, name.indexOf('/') !== -1);
测试代码记得移除哦

2022-04-18 02:39 UTC, NuoHui commented on src/action-sheet/action-sheet.wxs
> +  console.log(name, name.indexOf('/') !== -1);
我得问题，我稍后改下。

2022-04-18 02:43 UTC, LeeJim commented on src/action-sheet/action-sheet.ts
> +    defaultVisible: {
这里和 props.ts 重复了，可以移除

2022-04-18 02:48 UTC, LeeJim commented on src/action-sheet/action-sheet.ts
> +      this.setData({ visible: false });
可以的

2022-04-18 02:59 UTC, LeeJim commented on src/action-sheet/README.md
> +selected | `{selected: ActionSheetItem | String, index: number}` | 选择菜单项时触发
参数应该是 `(selected: ActionSheetItem | string, index: number)`

2022-04-18 05:00 UTC, NuoHui commented on src/action-sheet/action-sheet.ts
> +    defaultVisible: {
嗯 已删除了

2022-04-18 05:01 UTC, NuoHui commented on src/action-sheet/README.md
> +selected | `{selected: ActionSheetItem | String, index: number}` | 选择菜单项时触发
嗯 文档重新reveiw了下，也完善了其他地方

2022-04-18 05:01 UTC, NuoHui commented on src/action-sheet/action-sheet.wxs
> +  console.log(name, name.indexOf('/') !== -1);
已经移除

2022-04-18 06:20 UTC, LeeJim approved these changes
LGTM

2022-04-18 06:20 UTC, merged