[WIP](notice-bar): update props
Tencent/tdesign-miniprogram pull request #354
Opened 2022-04-15 02:15 UTC by anlyyao

2022-04-19 08:18 UTC, LeeJim requested changes

2022-04-19 08:18 UTC, LeeJim commented on src/notice-bar/notice-bar.ts
> +  created() {
生命周期函数应该放在 lifetimes 的对象里

2022-04-19 08:18 UTC, LeeJim commented on src/notice-bar/notice-bar.ts
> +      }, durationTime);
这里需要加上 delay

2022-04-20 03:05 UTC, LeeJim requested changes

2022-04-20 03:05 UTC, LeeJim commented on src/notice-bar/notice-bar.wxml
> +  <!-- extre -->
不存在这个单词吧？应该是 extra

2022-04-20 03:05 UTC, LeeJim commented on src/notice-bar/notice-bar.ts
> +      this.triggerEvent('extre', { self: this });
事件不对，应该是 click，然后 `{ trigger: 'extra' }`

2022-04-20 03:19 UTC, LeeJim commented on src/notice-bar/notice-bar.ts
> +      this.show();
这里应该判断 visible 才 show

2022-04-20 03:19 UTC, LeeJim commented on src/notice-bar/notice-bar.ts
> +      if (!visible) {
这里如果 visible 的话，应该调用 show 方法

2022-04-20 03:19 UTC, LeeJim commented on src/notice-bar/notice-bar.ts
> +      requestAnimationFrame(() => {
初始化动画之前，是不是应该判断该 notice-bar 是否存在动画？

2022-04-20 04:40 UTC, anlyyao commented on src/notice-bar/notice-bar.ts
> +      requestAnimationFrame(() => {
show()里面，在 this.initAnimation()之前，先调了this.clearNoticeBarAnimation()方法

2022-04-20 08:33 UTC, LeeJim approved these changes

2022-04-20 08:33 UTC, merged