fix(loading): correct classname
Tencent/tdesign-miniprogram pull request #36
Opened 2021-12-22 08:40 UTC by LeeJim

Loading: 修正 classname & 代码优化

2021-12-22 08:58 UTC, jin0209 commented on src/loading/loading.wxml
> +    class="{{prefix}}-class-indicator {{classPrefix}}__bar {{progress < 0 ? classPrefix + '__bar-animation' :progress < 100 ? classPrefix + '__bar-static': '' }} {{progress >= 100 || !loading ? class
{{classPrefix}}__bar-{{progress < 0 ? 'animation' : progress < 100 ? 'static' :  '' }}

2021-12-23 03:33 UTC, LeeJim commented on src/loading/loading.wxml
> +    class="{{prefix}}-class-indicator {{classPrefix}}__bar {{progress < 0 ? classPrefix + '__bar-animation' :progress < 100 ? classPrefix + '__bar-static': '' }} {{progress >= 100 || !loading ? class
好

2021-12-24 02:19 UTC, JJunYang requested changes

2021-12-24 02:19 UTC, JJunYang commented on src/loading/loading.less
> +    &-static {
-static 是否改为--static表示状态

2021-12-24 02:19 UTC, JJunYang commented on src/loading/loading.less
> +    &-loaded {
同上static，--loaded表示状态

2021-12-27 07:20 UTC, LeeJim commented on src/loading/loading.less
> +    &-static {
done

2021-12-27 07:20 UTC, LeeJim commented on src/loading/loading.less
> +    &-loaded {
done

2021-12-27 07:21 UTC, JJunYang approved these changes

2021-12-27 07:21 UTC, merged