feat(image-viewer): add image-viewer component
Tencent/tdesign-miniprogram pull request #408
Opened 2022-04-27 15:25 UTC by NuoHui

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-04-28 07:45 UTC, LeeJim requested changes

2022-04-28 07:45 UTC, LeeJim commented on src/image-viewer/image-viewer.wxml
> +      <view class="{{classPrefix}}__nav-index">{{currentSwiperIndex + 1}}/{{images.length}}</view>
`wx:if="{{showIndex}}"` 应该放在这个位置？
目前的问题是，showIndex = false 的时候，close & delete 都不展示了

2022-04-28 07:45 UTC, LeeJim commented on src/image-viewer/image-viewer.ts
> +    onVisibleChange() {
我感觉这个应该也是 close，但返回的参数增加一个 trigger = overlay，意思是点击遮罩层关闭的。
然后移除这个事件

2022-04-28 07:45 UTC, LeeJim commented on src/image-viewer/image-viewer.ts
> +      this._trigger('close', { index: this.data.currentSwiperIndex });
这个close返回的参数增加两个，trigger = button，visible = false

2022-04-28 07:45 UTC, LeeJim commented on src/image-viewer/image-viewer.ts
> +      event: 'visible-change',
应该是close

2022-04-28 07:51 UTC, NuoHui commented on src/image-viewer/image-viewer.wxml
> +      <view class="{{classPrefix}}__nav-index">{{currentSwiperIndex + 1}}/{{images.length}}</view>
嗯 这个我是在文档说了，操作按钮展示前提是 展示翻页，那这里我统一下，各个都是独立的

2022-04-28 12:53 UTC, NuoHui commented on src/image-viewer/image-viewer.ts
> +    onVisibleChange() {
嗯， 有道理，这里统一收敛了

2022-04-28 12:53 UTC, NuoHui commented on src/image-viewer/image-viewer.ts
> +      this._trigger('close', { index: this.data.currentSwiperIndex });
嗯 重新改了

2022-04-28 12:53 UTC, NuoHui commented on src/image-viewer/image-viewer.ts
> +      event: 'visible-change',
嗯 已改

2022-04-29 01:19 UTC, LeeJim approved these changes
LGTM

2022-04-29 01:19 UTC, merged