feat(avatar): css starndard
Tencent/tdesign-miniprogram pull request #42
Opened 2021-12-22 12:12 UTC by jin0209

2021-12-23 02:37 UTC, LeeJim requested changes

2021-12-23 02:37 UTC, LeeJim commented on src/avatar/avatar.wxml
> +    class="{{prefix}}-badge__{{shape === 'circle' ? 'circle' : 'round'}}"
这里感觉是 modifier ，应该用 `--` ？

2021-12-24 07:02 UTC, jin0209 commented on src/avatar/avatar.wxml
> +    class="{{prefix}}-badge__{{shape === 'circle' ? 'circle' : 'round'}}"
这里是对应的不同元素

2021-12-26 02:32 UTC, LeeJim approved these changes
LGTM

2021-12-26 02:32 UTC, LeeJim commented on src/avatar/avatar.wxml
> +    class="{{prefix}}-badge__{{shape === 'circle' ? 'circle' : 'round'}}"
ok

2021-12-26 02:32 UTC, merged