fix(action-sheet): fix the multiple pages error
Tencent/tdesign-miniprogram pull request #477
Opened 2022-05-25 12:58 UTC by Rimin

### 🤔 这个 PR 的性质是？

- [✅ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

1. 这里主要是修改 action-sheet 组件直接在 example 示例项目里引入原生组件在 QQ 小程序下报错且无法使用的问题；
<img width="949" alt="image" src="https://user-images.githubusercontent.com/24391778/170237226-090103a2-0902-4e9e-b34c-8d4647e71fbe.png">

2. 和 message 、 dialog 等组件导出组件方法的写法不一致；所以这次的修改是和他们统一；

3.  搜索了一下发现较早版本的微信小程序好像也有过这种问题：见 https://github.com/NervJS/taro/issues/6084

![image](https://user-images.githubusercontent.com/24391778/170265796-8f8f722a-cab3-41ed-8963-0ad5f50251c6.png)

所以像这样直接引入原组件的做法后续应该不推荐比较好？

### 📝 更新日志

- fix(action-sheet):  fix the multiple pages error

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- 已验证修改后在微信及 QQ 小程序都可以运行；

2022-05-31 02:56 UTC, LeeJim requested changes

2022-05-31 02:56 UTC, LeeJim commented on src/action-sheet/index.ts
> +  show(options: ActionSheetShowOption) {
这里可以写成
```js
export default {
  show
}

2022-05-31 06:18 UTC, Rimin commented on src/action-sheet/index.ts
> +  show(options: ActionSheetShowOption) {
已修改

2022-06-09 02:59 UTC, LeeJim approved these changes
LGTM

2022-08-05 05:54 UTC, closed without merging