feat: picker api update
Tencent/tdesign-miniprogram pull request #478
Opened 2022-05-26 02:52 UTC by wutianSweet

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [x] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(Picker):  API 重构，Picker 新增 value 属性，Picker 移除 value 属性；confirm 更新为 change， 原先的 change 事件 更新为 pick

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-05-30 09:27 UTC, LeeJim requested changes

2022-05-30 09:27 UTC, LeeJim commented on src/picker/README.md
> +cancel-btn | String / Object | 取消 | 取消按钮文字。TS 类型：`string | ButtonProps` | N
目前还是只支持 string

2022-05-30 09:27 UTC, LeeJim commented on src/picker/README.md
> +confirm-btn | String / Object | 确认 | 确定按钮文字。TS 类型：`string | ButtonProps`，[Button API Documents](./button?tab=api)。[详细类型定义](https://github.com/Tencent/tdesign-miniprogram/tree/develop/src/picker/type.
目前还是只支持 string

2022-05-30 09:27 UTC, LeeJim commented on src/picker/type.ts
> +import { TNode } from '../common/common';
这一行先手动删了吧，没用到

2022-05-30 09:27 UTC, LeeJim commented on src/picker/picker-item.ts
> +      const { options } = this.properties;
options 也可以从 data 里获取，因此可以和下面一行代码合并

2022-05-30 09:27 UTC, LeeJim commented on src/picker/picker.ts
> +      pickerColumns.forEach((child, index) => {
这部分逻辑是不是可以写到 picker-item 里面。
因为目前这样的写法效率较低，假设有 3 个 picker-item，就会执行 1 + 2 + 3 = 6 次。
写在 picker-item里面只需要执行 3 次。

2022-05-30 12:12 UTC, wutianSweet commented on src/picker/picker.ts
> +      pickerColumns.forEach((child, index) => {
1、这里的 6 次 是怎么算出来的， 如果有 3 列 现目前只会执行 3次
2、这部分逻辑这样写 主要是因为 picker 组件接受到的 value  没办法直接传给 picker-item, 需要通过这种方式进行通信

2022-05-31 14:54 UTC, LeeJim commented on src/date-time-picker/README.md
> +mode | String / Array | date | year: 年；month: 年月；date: 年月日；hour: 年月日时； minute: 年月日时分 TS 类型：`DateTimePickerMode` `type DateTimePickerMode = TimeModeValues | Array<TimeModeValues> ` `type TimeModeValue
默认值应该是 `'date'`。可以重新跑下 CLI 我修改好了

2022-06-01 07:57 UTC, wutianSweet commented on src/picker/README.md
> +cancel-btn | String / Object | 取消 | 取消按钮文字。TS 类型：`string | ButtonProps` | N
下次发布 修改这里 暂时先只支持 string

2022-06-01 07:58 UTC, wutianSweet commented on src/picker/README.md
> +confirm-btn | String / Object | 确认 | 确定按钮文字。TS 类型：`string | ButtonProps`，[Button API Documents](./button?tab=api)。[详细类型定义](https://github.com/Tencent/tdesign-miniprogram/tree/develop/src/picker/type.
下次发布 修改这里 暂时先只支持 string

2022-06-01 07:58 UTC, wutianSweet commented on src/picker/type.ts
> +import { TNode } from '../common/common';
已修改

2022-06-01 07:58 UTC, wutianSweet commented on src/date-time-picker/README.md
> +mode | String / Array | date | year: 年；month: 年月；date: 年月日；hour: 年月日时； minute: 年月日时分 TS 类型：`DateTimePickerMode` `type DateTimePickerMode = TimeModeValues | Array<TimeModeValues> ` `type TimeModeValue
已使用cli 重新生成文档

2022-06-01 09:14 UTC, merged