fix(loading): 修复text为空时，实际大小与视觉大小不一致问题
Tencent/tdesign-miniprogram pull request #621
Opened 2022-07-16 17:05 UTC by wanpan11

fix #618

### 🤔 这个 PR 的性质是？
- [x] 日常 bug 修复

### 🔗 相关 Issue
fix(loading): 修复text为空时，实际大小与视觉大小不一致问题
https://github.com/Tencent/tdesign-miniprogram/issues/618

### 📝 更新日志

- fix(loading): 修复text为空时，实际大小与视觉大小不一致问题

- [x] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-07-17 04:24 UTC, LeeJim requested changes

2022-07-17 04:24 UTC, LeeJim commented on src/loading/loading.wxml
> +    <view class="{{prefix}}-class-text" wx:if="{{text}}">
这个 if 加到 41 行合理些。
放在这里会导致 theme === 'error' 的情况被忽略

2022-07-17 06:03 UTC, wanpan11 commented on src/loading/loading.wxml
> +    <view class="{{prefix}}-class-text" wx:if="{{text}}">
确实😀

2022-07-17 14:53 UTC, LeeJim requested changes

2022-07-17 14:53 UTC, LeeJim commented on src/loading/loading.wxml
>          {{text}}
目前会存在一个问题，当要使用插槽的时候，text != null，但此时只想要插槽而不要 text
所以，建议这里加个 `text != 'slot' && text`

2022-07-18 02:26 UTC, wanpan11 commented on src/loading/loading.wxml
>          {{text}}
嗯呢 是我想的少了😁。

我这边试了下，好像 text 不会 slot 哎。🤔

- 组件
![image](https://user-images.githubusercontent.com/38714194/179436624-fc5f70d2-9310-46dd-9248-3cea4c0e1500.png)

- 示例
![image](https://user-images.githubusercontent.com/38714194/179436756-9ecd4ee9-0540-4fb1-9cd0-97d51397d661.png)

- 实际渲染
![image](https://user-images.githubusercontent.com/38714194/179436533-2efe1814-5503-4cbf-9671-780846d7b53b.png)

文档好像也没写 slot存在时 text = 'solt' 的情况哎

2022-07-18 02:56 UTC, LeeJim commented on src/loading/loading.wxml
>          {{text}}
文档我这边补一下

2022-07-18 02:57 UTC, LeeJim commented on src/loading/loading.wxml
>          {{text}}
如果不加上我说的逻辑，要使用插槽时如何使用？

2022-07-18 03:21 UTC, wanpan11 commented on src/loading/loading.wxml
>          {{text}}
是需要添加新的props text='slot' 吗?

![image](https://user-images.githubusercontent.com/38714194/179440326-41d8b94d-26a4-4034-b096-957184e2368c.png)

> 如果不加上我说的逻辑，要使用插槽时如何使用？

我查文章好像说小程序是不知道有没有传入 slot 的。有通过监听slot区域实现的方法但是感觉有点繁琐。
不知道 我理解的对不对🤔

2022-07-18 03:40 UTC, LeeJim commented on src/loading/loading.wxml
>          {{text}}
是的。小程序不知道是否传入了slot。所以TDesign这边的做法是，当一个属性既支持 slot 也支持其他类型的时候。默认当这个属性 = 'slot' 的时候，使用插槽。

2022-07-18 03:54 UTC, wanpan11 commented on src/loading/loading.wxml
>          {{text}}
> 是的。小程序不知道是否传入了 slot。所以 TDesign 这边的做法是，当一个属性既支持 slot 也支持其他类型的时候。默认当这个属性 = 'slot' 的时候，使用插槽。

好的。我开始没理解到，我还想传入slot的时候 text 好像不会等于 solt😂。那我改下提交啦

2022-07-18 06:13 UTC, LeeJim commented on src/loading/loading.wxml
>          {{text}}
嗯 今天能否提交。今天会发个版本

2022-07-18 07:34 UTC, LeeJim approved these changes
LGTM

2022-07-18 07:34 UTC, merged