docs(Grid): update code sample
Tencent/tdesign-miniprogram pull request #635
Opened 2022-07-19 11:09 UTC by anlyyao

### 🤔 这个 PR 的性质是？
- [x] 演示代码改进
- [x] 组件样式/交互改进

### 📝 更新日志

- style(Grid): 调整 `horizontal` 方向内容布局
- docs(Grid): 更新示例代码

2022-07-20 02:55 UTC, LeeJim requested changes
需对齐视觉稿

2022-07-20 03:24 UTC, anlyyao commented
1 已对齐视觉～～

2022-07-21 08:45 UTC, anlyyao commented
1

2022-07-23 14:35 UTC, LeeJim requested changes

2022-07-23 14:35 UTC, LeeJim commented on src/grid/README.md
> +--t-grid-bg-color | 宫格背景颜色
CSS Varaibles 统一改成 `--td` 开头

2022-07-25 07:06 UTC, LeeJim approved these changes
LGTM

2022-07-25 07:07 UTC, merged