docs(indexes): update code sample
Tencent/tdesign-miniprogram pull request #649
Opened 2022-07-21 02:48 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 演示代码改进

### 📝 更新日志

- docs(Indexes): 更新示例代码

2022-07-21 06:43 UTC, LeeJim requested changes

2022-07-21 06:43 UTC, LeeJim commented on src/indexes/_example/display/index.json
> +  "navigationBarBackgroundColor": "#fff",
上面两行有点多余

2022-07-21 08:45 UTC, anlyyao commented on src/indexes/_example/display/index.json
> +  "navigationBarBackgroundColor": "#fff",
1

2022-07-25 07:58 UTC, LeeJim approved these changes
LGTM

2022-07-25 07:58 UTC, merged