Docs/radio
Tencent/tdesign-miniprogram pull request #667
Opened 2022-07-26 11:54 UTC by wangyuan0108

### 🤔 这个 PR 的性质是？

- [x] 演示代码改进

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-07-31 15:44 UTC, LeeJim requested changes

2022-07-31 15:44 UTC, LeeJim commented on src/radio/_example/left-round/index.js
> +  methods: {},
缺了 onChange 事件

2022-07-31 15:44 UTC, LeeJim commented on src/radio/_example/right-round/index.js
> +  methods: {},
同样缺 onChange 事件

2022-08-02 13:51 UTC, wangyuan0108 commented on src/radio/_example/left-round/index.js
> +  methods: {},
ok

2022-08-03 07:23 UTC, LeeJim approved these changes
LGTM

2022-08-03 07:23 UTC, merged