feat(Swiper): support pagination-position
Tencent/tdesign-miniprogram pull request #669
Opened 2022-07-27 02:06 UTC by anlyyao

### 🤔 这个 PR 的性质是？
- [x] 新特性提交
- [x] 演示代码改进

### 📝 更新日志

- feat(Swiper): 支持 `paginationPosition`
- feat(Swiper): 新增 CSS Variable 调整 Swiper 导航器背景、内容颜色
- docs(Swiper): 更新示例代码

2022-07-27 03:20 UTC, LeeJim requested changes

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/_example/base/index.wxml
> +    <view class="item">{{index}}<image src="{{item.image}}" class="img" /></view>
`{{index}}`是多余的

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/swiper-nav.ts
> +  paginationPosition: boolean;
`boolean` ?

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/swiper-nav.less
> +    &-left .@{prefix}-swiper-nav__dots,
没有 left

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/swiper-nav.less
> +    &-right .@{prefix}-swiper-nav__dots,
没有 right

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/_example/custom/index.wxss
> +.item {
样式可以移除

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/_example/fraction/index.wxss
> +.item {
样式可以移除

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/_example/nav-btn/index.wxss
> +.item {
样式可以移除

2022-07-27 03:20 UTC, LeeJim commented on src/swiper/_example/base/index.wxml
> +    <view class="item">{{index}}<image src="{{item.image}}" class="img" /></view>
结构可以改到，将 image 放出来，移除 item

2022-07-27 05:02 UTC, anlyyao commented on src/swiper/swiper-nav.less
> +    &-left .@{prefix}-swiper-nav__dots,
分式导航器常用位置是top-left/top/top-right/bottom-left/bottom/bottom-right六个方位，但我觉得我们也需要考虑点状导航器的位置情况，点状导航器常用位置有bottom、left、right～～ 所以把left和right加进去了

2022-07-27 05:02 UTC, anlyyao commented on src/swiper/_example/custom/index.wxss
> +.item {
1

2022-07-27 05:02 UTC, anlyyao commented on src/swiper/_example/fraction/index.wxss
> +.item {
1

2022-07-27 05:02 UTC, anlyyao commented on src/swiper/_example/nav-btn/index.wxss
> +.item {
1

2022-07-27 05:03 UTC, anlyyao commented on src/swiper/_example/base/index.wxml
> +    <view class="item">{{index}}<image src="{{item.image}}" class="img" /></view>
1

2022-07-27 05:03 UTC, anlyyao commented on src/swiper/_example/base/index.wxml
> +    <view class="item">{{index}}<image src="{{item.image}}" class="img" /></view>
1

2022-07-27 05:03 UTC, anlyyao commented on src/swiper/swiper-nav.ts
> +  paginationPosition: boolean;
已修改

2022-07-29 09:03 UTC, LeeJim commented on src/swiper/swiper-nav.less
> +    &-left .@{prefix}-swiper-nav__dots,
ok

2022-07-29 09:06 UTC, LeeJim approved these changes
LGTM

2022-07-29 09:06 UTC, merged