Docs/toast
Tencent/tdesign-miniprogram pull request #676
Opened 2022-07-28 09:58 UTC by CodingOnStar

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [x] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
[#574]

更新toast官网文档及demo
### 💡 需求背景和解决方案

### 📝 更新日志
更新toast官网文档及demo

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-07-29 08:48 UTC, LeeJim requested changes
示例代码改造的目的是，每个示例对应的代码用户可以直接复制使用。

不应该包含其他展示用的代码

2022-07-29 08:50 UTC, LeeJim commented
可以参考 drawer 来改造

2022-07-29 12:27 UTC, CodingOnStar commented
> 示例代码改造的目的是，每个示例对应的代码用户可以直接复制使用。
> 
> 不应该包含其他展示用的代码

谢谢指导。这样理解的话，貌似toast比较特殊，文档可能并不太需要更改？

2022-08-03 07:35 UTC, LeeJim commented
> > 示例代码改造的目的是，每个示例对应的代码用户可以直接复制使用。
> > 不应该包含其他展示用的代码
> 
> 谢谢指导。这样理解的话，貌似toast比较特殊，文档可能并不太需要更改？

还是需要的，不过可能不太好描述。
现在的代码也是满足需要，我先合并吧。后面我再优化一下。

2022-08-03 07:35 UTC, LeeJim approved these changes

2022-08-03 07:35 UTC, merged