test(Tag): add unit test
Tencent/tdesign-miniprogram pull request #743
Opened 2022-08-10 01:13 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [x] 测试用例

### 📝 更新日志

- fix(Tag): 修复 disabled 为true时，closable 无效的问题
- fix(Tag): 修复 maxWidth 输入为字符时，宽度计算错误问题
- test(Tag): 完善单元测试

2022-08-10 03:16 UTC, LeeJim requested changes

2022-08-10 03:16 UTC, LeeJim commented on src/tag/tag.ts
> +      const width = isNumber(maxWidth) ? `${maxWidth}px` : maxWidth;
这个需要考虑个场景，如果传入'34'的话，应该如何处理？

2022-08-10 03:16 UTC, LeeJim commented on src/tag/__test__/index.test.js
> +    $tag.instance.setClass();
不应该手动调用；下面的同理

2022-08-10 03:16 UTC, LeeJim commented on src/tag/__test__/index.test.js
> +    expect($tag.data.className.includes('t-tag--disabled')).toBe(true);
这里要重新 querySelector；下面的同理

2022-08-10 08:42 UTC, LeeJim requested changes

2022-08-10 08:42 UTC, LeeJim commented on src/tag/__test__/index.test.js
> +    await simulate.sleep(10);
这个应该是多余的

2022-08-10 08:42 UTC, LeeJim commented on src/tag/__test__/index.test.js
> +    expect($tag.data.className.includes('t-tag--theme-default')).toBe(true);
不应该是读 data 的值，应该是取 DOM 的 class。
下面同理

2022-08-10 12:49 UTC, anlyyao commented on src/tag/__test__/index.test.js
> +    $tag.instance.setClass();
1

2022-08-10 12:50 UTC, anlyyao commented on src/tag/tag.ts
> +      const width = isNumber(maxWidth) ? `${maxWidth}px` : maxWidth;
改用 common/utils下的 isNumber函数，做浮点数正则匹配了～

2022-08-11 06:35 UTC, LeeJim approved these changes

2022-08-11 06:37 UTC, merged