test(search): add unit test
Tencent/tdesign-miniprogram pull request #790
Opened 2022-08-23 12:59 UTC by Perisiguiendo

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-08-25 07:52 UTC, LeeJim requested changes

2022-08-25 07:52 UTC, LeeJim commented on src/search/__test__/index.test.js
> +      expect(
这里缺了 matcher，只有 expect。所以总是通过的

2022-08-25 07:52 UTC, LeeJim commented on src/search/__test__/index.test.js
> +      expect(
同上

2022-08-25 08:36 UTC, Perisiguiendo commented on src/search/__test__/index.test.js
> +      expect(
已修复

2022-08-26 06:44 UTC, LeeJim approved these changes
LGTM

2022-08-26 06:45 UTC, merged