test(switch): add unit test
Tencent/tdesign-miniprogram pull request #791
Opened 2022-08-23 13:00 UTC by Perisiguiendo

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- test(Switch): 增加单元测试

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-08-25 07:00 UTC, LeeJim requested changes

2022-08-25 07:00 UTC, LeeJim commented on src/switch/__test__/index.test.js
> +      expect(onChange.mock.calls[0][0].detail).toStrictEqual({ value: false });
这个 expect 应该总是 true 的。不要手动 dispatch change，应该模拟点击

2022-08-25 08:35 UTC, Perisiguiendo commented on src/switch/__test__/index.test.js
> +      expect(onChange.mock.calls[0][0].detail).toStrictEqual({ value: false });
已修复，辛苦看一下

2022-08-26 06:50 UTC, LeeJim approved these changes
LGTM

2022-08-26 06:50 UTC, merged