test(message): add unit message
Tencent/tdesign-miniprogram pull request #802
Opened 2022-08-25 15:47 UTC by AntzyMo

test/message

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [x] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

test(Message): 新增单元测试

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-08-26 07:46 UTC, LeeJim requested changes

2022-08-26 07:46 UTC, LeeJim commented on src/message/__test__/index.test.js
> +      // console.log(indicator.dom.getAttribute('class'));
这行可以删掉

2022-08-26 07:46 UTC, LeeJim commented on src/message/__test__/index.test.js
> +      comp.setData({ visible: false });
上面两行看起来是多余的

2022-08-26 07:46 UTC, LeeJim commented on src/message/__test__/index.test.js
> +      $closeBtn.dispatchEvent('close-btn-click');
这里应该是 tap 事件

2022-08-26 08:07 UTC, AntzyMo commented on src/message/__test__/index.test.js
> +      // console.log(indicator.dom.getAttribute('class'));
是注释那行吗？还是52-55行

2022-08-26 08:49 UTC, LeeJim commented on src/message/__test__/index.test.js
> +      // console.log(indicator.dom.getAttribute('class'));
注释那行

2022-08-26 12:54 UTC, AntzyMo commented on src/message/__test__/index.test.js
> +      $closeBtn.dispatchEvent('close-btn-click');
tap的话报 TypeError: style.replace is not a function这个错了

2022-08-29 09:23 UTC, LeeJim requested changes

2022-08-29 09:23 UTC, LeeJim commented on src/message/__test__/index.test.js
> +      $closeBtn.dispatchEvent('close-btn-click');
这行代码怎么没看到哪里有出现过？

2022-08-29 09:23 UTC, LeeJim commented on src/message/__test__/index.test.js
> +      $closeBtn.dispatchEvent('close-btn-click');
这行代码怎么没见过？

2022-08-31 07:09 UTC, LeeJim commented
看了下，测试覆盖率都是小于80的哦

2022-08-31 07:11 UTC, AntzyMo commented
> 看了下，测试覆盖率都是小于80的哦

好的 我再去写写

2022-08-31 11:35 UTC, LeeJim commented
> > 看了下，测试覆盖率都是小于80的哦
> 
> 好的 我再去写写

可以参考下 dialog 和 toast

2022-09-01 07:05 UTC, LeeJim commented
> 

是不是按钮不存在，`action === false` ?

2022-09-01 09:26 UTC, AntzyMo commented
> > 
> 
> 是不是按钮不存在，`action === false` ?

可是我能拿到action的内容

2022-09-02 16:17 UTC, AntzyMo commented
@LeeJim  这次message的测试我处理的不是很好，我这边的window和mac运行测试的环境都报很多问题，导致有点难进行下去了，不过现在的测试覆盖率有是三个是75% 以上了，然后`fix: 测试覆盖率提升到75%` 这个才是提交代码，然后不知道怎么了，把其他也提交上去的，不好意思，没有达到您想要的80%的要求

2022-09-07 09:19 UTC, LeeJim commented
OK。我这边来跟进处理完

2022-09-07 10:03 UTC, closed without merging