feat(Icon): name supports image types
Tencent/tdesign-miniprogram pull request #828
Opened 2022-09-01 02:01 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 新特性提交

### 🔗 相关 Issue
#815 

### 📝 更新日志

- feat(Icon):  `name` 支持图片链接
- fix(Icon): `size` 不在支持 `middle`、`small`等关键字，默认单位 `px`

2022-09-01 03:05 UTC, LeeJim commented on src/notice-bar/__test__/__snapshots__/index.test.js.snap
> +            style="color: ; font-size: "
无值的时候，避免写值

2022-09-01 03:24 UTC, LeeJim requested changes

2022-09-01 03:24 UTC, LeeJim commented on src/icon/icon.ts
> +    componentPrefix: prefix,
这个变量名统一使用 prefix 就行了

2022-09-01 03:24 UTC, LeeJim commented on src/icon/icon.ts
> +        iconStyle: isImage
这一行可以改下写法：
```js
const size = isImage ? { width: sizeValue, height: sizeValue } : {};
this.setData({
  iconStyle: styles({
    color,
    'font-size': sizeValue,
    ...size,
    ...customStyle,
  })
})

2022-09-01 03:24 UTC, LeeJim commented on src/input/__test__/__snapshots__/index.test.js.snap
> +              style="0: f; 1: o; 2: n; 3: t; 4: -; 5: s; 6: i; 7: z; 8: e; 9: :; 10:  ; 11: 3; 12: 9; 13: r; 14: p; 15: x; color: ; font-size: "
这里就对样式解析错误了，把字符串当数组处理了

2022-09-02 01:14 UTC, anlyyao commented on src/notice-bar/__test__/__snapshots__/index.test.js.snap
> +            style="color: ; font-size: "
1

2022-09-02 01:14 UTC, anlyyao commented on src/icon/icon.ts
> +        iconStyle: isImage
1

2022-09-02 01:14 UTC, anlyyao commented on src/input/__test__/__snapshots__/index.test.js.snap
> +              style="0: f; 1: o; 2: n; 3: t; 4: -; 5: s; 6: i; 7: z; 8: e; 9: :; 10:  ; 11: 3; 12: 9; 13: r; 14: p; 15: x; color: ; font-size: "
1

2022-09-02 06:43 UTC, LeeJim commented on src/icon/icon.ts
> +    judgeImage(val) {
这个不需要单独抽象一个方法

2022-09-02 06:47 UTC, LeeJim commented on src/icon/icon.ts
> +    componentPrefix: prefix,
懂了。和图标本身的属性 prefix 冲突

2022-09-02 07:36 UTC, anlyyao commented on src/icon/icon.ts
> +    judgeImage(val) {
1

2022-09-02 09:14 UTC, LeeJim approved these changes

2022-09-02 10:51 UTC, merged