feat(action-sheet): add unit test for action-sheet
Tencent/tdesign-miniprogram pull request #832
Opened 2022-09-01 16:05 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 测试用例

### 📝 更新日志

- feat(ActionSheet): 新增单元测试
- fix(ActionSheet): 移除 `close` 事件

2022-09-02 07:52 UTC, LeeJim commented
没生成徽章

2022-09-05 02:28 UTC, LeeJim commented
分支覆盖率只有72

2022-09-05 03:20 UTC, anlyyao commented
@LeeJim  已提升分支覆盖率

2022-09-05 08:52 UTC, LeeJim requested changes

2022-09-05 08:52 UTC, LeeJim commented on src/action-sheet/show.ts
> +  const { context, selector, ...otherOptions } = { ...options };
需要补充个默认值 `selector  = '#t-action-sheet'`

2022-09-05 08:52 UTC, LeeJim commented on src/action-sheet/show.ts
> +  if (instance) {
当 instance 不存在是，需告警，可以不用返回 `Project.reject()`.
使用 console.error：
```
if (!instance) {
  console.error('')
}
return instance
```

2022-09-05 09:10 UTC, anlyyao commented on src/action-sheet/show.ts
> +  const { context, selector, ...otherOptions } = { ...options };
1

2022-09-05 09:10 UTC, anlyyao commented on src/action-sheet/show.ts
> +  if (instance) {
已补充～

2022-09-05 09:18 UTC, LeeJim approved these changes
LGTM

2022-09-05 09:18 UTC, merged