test(indexes): add the testing case of Indexes Component
Tencent/tdesign-miniprogram pull request #850
Opened 2022-09-07 08:15 UTC by CodingOnStar

#701

### 🤔 这个 PR 的性质是？

- [x] 测试用例

### 🔗 相关 Issue
#701 

添加Index的测试覆盖
### 💡 需求背景和解决方案

### 📝 更新日志
添加Index的测试覆盖

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-09-07 08:31 UTC, LeeJim commented
需用执行下 `npm run badge indexes` 生成测试覆盖率徽章

2022-09-07 08:56 UTC, LeeJim requested changes

2022-09-07 08:56 UTC, LeeJim commented on src/indexes/__test__/index.test.js
> +    expect($scrollView.dom.scrollTop).toEqual(50);
这个 expect 是没有作用的。这里测试的是 simulate.scroll 是否正常运行，不是我们需要测试的

2022-09-07 08:56 UTC, LeeJim commented on src/indexes/__test__/index.test.js
> +    expect(comp).toMatchSnapshot();
这个 snapshot 也不是很有必要。
反而需要 expect 当前滚动到某个地方之后，锚点是否正常切换了。

还有就是 点击锚点 之后 content 是否滚动到指定位置了

2022-09-07 08:56 UTC, LeeJim commented on src/indexes/__test__/index.test.js
> +    touch();
这里touch完之后，没有 expect，意味着上面的 touch 没有验证结果

2022-09-14 02:46 UTC, LeeJim commented
不要生成其他组件的徽章，只需要生成 Indexes 的徽章

2022-09-14 03:13 UTC, CodingOnStar commented
> 不要生成其他组件的徽章，只需要生成 Indexes 的徽章

嗯嗯 已经revert修正了

2022-09-14 07:03 UTC, LeeJim approved these changes

2022-09-14 07:13 UTC, LeeJim approved these changes
LGTM

2022-09-14 07:13 UTC, merged