fix(Icon): resolve character concatenation error
Tencent/tdesign-miniprogram pull request #950
Opened 2022-10-28 02:59 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复

### 📝 更新日志

- fix(Icon): 修复 `customStyle` 属性无效。（`icon`、`size` 优先级高于 `customStyle`）

2022-10-28 08:02 UTC, LeeJim approved these changes

2022-10-28 08:05 UTC, LeeJim requested changes
样式优先级不要变更

2022-10-28 08:20 UTC, anlyyao commented
@LeeJim  👌

2022-10-31 03:24 UTC, LeeJim approved these changes

2022-10-31 03:24 UTC, merged